This code will generate the feature vector, using sub grids to calculate the overlap

In [1]:
import pandas as pd
#pd.set_option('display.max_rows', None)
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib import path
import os
import cartopy.crs as ccrs
import cartopy
import numpy as np
import netCDF4 as nc
np.set_printoptions(threshold=100000)
from shapely.geometry import Polygon, Point, MultiPoint
from shapely.ops import cascaded_union
from datetime import datetime, timedelta
import time
import warnings
warnings.filterwarnings('ignore')
from os.path import exists


##  Step 0. Throw out fires that have 0 viirs detects on any day. (fires are already filtered to be in the right lat/lon range

In [2]:
# load in the polygons and attributes
fire_polygons = gpd.read_file('fire_polygons_only.geojson')
fire_attributes = pd.read_csv('fire_polygons_attributes.csv')
incidents = pd.read_csv('unique_fires.csv')
print(len(fire_polygons), len(fire_attributes), len(incidents))

#throw out fires that have 0 days with detects
daily_drop_inds = []
incident_drop_inds = []
for item in incidents['Incident Number']:
    pts = fire_attributes['Number of VIIRS points'].values[fire_attributes['Incident Number']==item]
    if len(pts[pts==0])==len(pts):
        #print(item, 'oops all zeros')
        daily_drop_inds = np.append(daily_drop_inds, np.where(fire_attributes['Incident Number']==item)[0])
        incident_drop_inds = np.append(incident_drop_inds, np.where(incidents['Incident Number']==item)[0])

daily_drop_inds = [int(p) for p in daily_drop_inds]
#print(daily_drop_inds)

fire_attributes = fire_attributes.drop(labels= daily_drop_inds)
fire_attributes = fire_attributes.drop(labels='Unnamed: 0', axis=1)
fire_polygons = fire_polygons.drop(labels = daily_drop_inds)
incidents = incidents.drop(labels = incident_drop_inds)
print(len(fire_polygons), len(fire_attributes), len(incidents))

fire_attributes


22280 22280 1354
19137 19137 1036


Incident Number      Fire Name Current Day   Lat Fire    Lon Fire  \
5           10662684.0  PAINTED WAGON  2019-04-08  33.786944 -112.753333   
6           10662684.0  PAINTED WAGON  2019-04-09  33.786944 -112.753333   
7           10662684.0  PAINTED WAGON  2019-04-10  33.786944 -112.753333   
8           10663171.0  LONE MOUNTAIN  2019-05-26  33.808056 -105.738611   
9           10663171.0  LONE MOUNTAIN  2019-05-27  33.808056 -105.738611   
...                ...            ...         ...        ...         ...   
22275       11980587.0        CREEK 5  2020-12-25  33.402646 -117.266795   
22276       11980587.0        CREEK 5  2020-12-26  33.402646 -117.266795   
22277       11980587.0        CREEK 5  2020-12-27  33.402646 -117.266795   
22278       11980587.0        CREEK 5  2020-12-28  33.402646 -117.266795   
22279       11980949.0        CREEK 5  2020-12-24  33.407667 -117.269667   

       Number of VIIRS points  
5                         3.0  
6                         0.0  
7                         0.0  
8                         0.0  
9                         0.0  
...                       ...  
22275                    16.0  
22276                     0.0  
22277                     0.0  
22278                     0.0  
22279                     2.0  

[19137 rows x 6 columns]

## 1. Figure out the start and end date we will use for each fire

In [ ]:
# first check what fraction of the fire lifetimes are 0 days
for item in incidents['Incident Number']:
    pts = fire_attributes['Number of VIIRS points'].values[fire_attributes['Incident Number']==item]
    #print(len(np.where(pts==0)[0]))
    print('The fire lifetime is ', len(np.where(pts!=0)[0])*100/len(pts), '% nonzero detections')

In [3]:
keep_days = []
for item in incidents['Incident Number']:
    pts = fire_attributes['Number of VIIRS points'].values[fire_attributes['Incident Number']==item]
    dys = fire_attributes['Current Day'].values[fire_attributes['Incident Number']==item]
    nonzero = np.where(pts!=0)[0]
    first_day = dys[nonzero[0]]
    last_day = dys[nonzero[len(nonzero)-1]]
    keep_days = np.append(keep_days, np.where((fire_attributes['Incident Number']==item)&(fire_attributes['Current Day']>=first_day)&(fire_attributes['Current Day']<=last_day))[0])

keep_days = [int(p) for p in keep_days]
print(len(keep_days))
fire_attributes = fire_attributes.iloc[keep_days, :]
fire_polygons = fire_polygons.iloc[keep_days, :]
fire_attributes = fire_attributes.reset_index(drop=True) #reset the indices beecause we dropped some
fire_polygons = fire_polygons.reset_index(drop=True) #reset the indices beecause we dropped some

fire_polygons



8161


geometry
0     POLYGON ((-112.75455 33.78632, -112.76012 33.7...
1     POLYGON ((-105.73275 33.80235, -105.73861 33.8...
2     POLYGON ((-105.73275 33.80235, -105.73861 33.8...
3     POLYGON ((-105.73275 33.80235, -105.73861 33.8...
4     POLYGON ((-105.73275 33.80235, -105.73861 33.8...
...                                                 ...
8156  POLYGON ((-112.11669 34.11898, -112.12564 34.1...
8157  POLYGON ((-117.03702 33.90632, -117.04484 33.9...
8158  POLYGON ((-117.27595 33.37881, -117.27495 33.3...
8159  POLYGON ((-117.29549 33.36558, -117.29713 33.4...
8160  POLYGON ((-117.27595 33.37881, -117.26967 33.4...

[8161 rows x 1 columns]

## 2. Loop through the days and get the raw features (temp at different pressure levels, wind, pressure, precip, terrain info) and the labels (QFED PM2.5 from the next day)

In [ ]:
ndays=2
# dictionaries that track the variables, dimensions, times and levels
varis = {'/STAGEIV/ST4.*12.24h.nc':['A_PCP_GDS5_SFC_acc24h'], 
         '/STAGEIV/st4_conus.*12.24h.nc':['APCP_P8_L1_GST0_acc']}
print(varis['/STAGEIV/st4_conus.*12.24h.nc'])
#0=lat, 1=lon, 2=time, 3=level 
dims = {'/STAGEIV/ST4.*12.24h.nc':['g5_lat_0', 'g5_lon_1'], 
        '/STAGEIV/st4_conus.*12.24h.nc':['gridlat_0', 'gridlon_0']}

times = {'TLML':12, 'QLML':12, 'SPEEDLML':12, 'PS':12, 'T':12, 'QV':12, 'biomass':12}
levels = {'T':[500, 700], 'QV':[700]} 
file_suffix = '.nc4'

#pre-allocate the data frame
num_days = len(fire_attributes)
fire_features = gpd.GeoDataFrame({'Incident Number': np.nan*np.zeros(num_days), 'Fire Name': np.nan*np.zeros(num_days), 
                             'Current Day': np.nan*np.zeros(num_days), 'Lat Fire': np.nan*np.zeros(num_days), 
                             'Lon Fire': np.nan*np.zeros(num_days), 'Number of VIIRS points': np.nan*np.zeros(num_days),
                             'A_PCP_GDS5_SFC_acc24h_0':np.nan*np.zeros(num_days),'APCP_P8_L1_GST0_acc_0':np.nan*np.zeros(num_days),
                            'A_PCP_GDS5_SFC_acc24h_1':np.nan*np.zeros(num_days),'APCP_P8_L1_GST0_acc_1':np.nan*np.zeros(num_days),
                            'geometry': np.nan*np.zeros(num_days)}) # pre-allocate the dataframe
#'fccs': np.nan*np.zeros(num_days),'slp': np.nan*np.zeros(num_days),'asp': np.nan*np.zeros(num_days), 
fire_features['Incident Number'] = fire_attributes['Incident Number'].values
fire_features['Fire Name'] = fire_attributes['Fire Name'].values
fire_features['Current Day'] = fire_attributes['Current Day'].values
fire_features['Lat Fire'] = fire_attributes['Lat Fire'].values
fire_features['Lon Fire'] = fire_attributes['Lon Fire'].values
fire_features['Number of VIIRS points'] = fire_attributes['Number of VIIRS points'].values
fire_features['geometry'] = fire_polygons['geometry'].values

#print(fire_features)
unique_days = np.unique(fire_features['Current Day'].values)
#print(np.where(unique_days=='2020-07-5'))
print(len(unique_days))
for dd in range(len(unique_days)):
    for dyf in range(ndays):
        date=np.datetime64(unique_days[dd])+np.array(dyf, 'timedelta64[D]')
        print(date)
        date=str(date)
        yr = date[0:4]
        mo = date[5:7]
        dy = date[8:10]
        print(yr, mo,dy)
        #find the polygons for the given day
        # assign i index based on date i=0 for dates <= 20200727, i = 1 for dates > 20200727
        if np.datetime64(date)<=np.datetime64('2020-07-27'):
            i = '/STAGEIV/ST4.*12.24h.nc'
        else:
            i = '/STAGEIV/st4_conus.*12.24h.nc'
        #get the path to the file
        data_path = '/data2/lthapa/'+yr+i
        if '*' in data_path:
            data_path = data_path.replace('*', yr+mo+dy)
        if np.datetime64(date)>=np.datetime64('2020-09-01') and np.datetime64(date)<=np.datetime64('2020-09-30'):
            data_path = data_path.replace('400', '401')

        #load the file in as a netcdf dataset
        print(data_path)
        dat = nc.Dataset(data_path)

        ndims = len(dims[i])
        lat = dat[dims[i][0]][:]
        lon = dat[dims[i][1]][:]
        #print(lat)
        #print(lat.shape, lon.shape)

        #calculate the areas of the lat/lon grid for the DATASET
        lat_corners, lon_corners = calculate_grid_cell_corners(lat, lon)
        inds = np.where(fire_features['Current Day']==unique_days[dd])[0]
        polys = fire_features['geometry'].iloc[inds].values

        for p in range(len(inds)):
            tic = time.time()
            #add a halo to the polygon
            poly = polys[p]
            poly_buff = poly.buffer(2)
            poly_series = gpd.GeoSeries(poly)
            # get the bounds of the buffered polygon

            w,s,e,n = poly_buff.bounds
            #print(w,s,e,n)
            i0, i1, j0, j1 =  bbox2ij(lon, lat, [w, e, s, n])

            #lat_sub_inds, lon_sub_inds = np.where((lat>=s)&(lat<=n)&(lon>=w)&(lon<=e))
            #print(lat_sub_inds, lon_sub_inds)

            #tic = time.time()
            overlaps = calculate_overlaps(lat,lon,lat_corners,lon_corners,j0,j1,i0,i1, poly) #calculate the overlap between the poly and the lat/lon grid
            print(np.where(overlaps!=0))
            #toc = time.time()
            #print('Time elapsed for calculating overlaps for polygon:', toc-tic)
            for j in varis[i]: #loop over the variable names, which are lists
                var = dat[j][:,:].data
                var[var==1e20] = np.nan
                #print('the dimensions of', j, 'are', var.shape, 'and', j, 'has', ndims, 'dimensions')
                #select the times and levels we need
                var_weighted = np.multiply(var,overlaps)
                var_ave = np.nansum(var_weighted)
                print(var_ave)
                name_in_table = j+'_'+str(dyf)
                fire_features.loc[inds[p],name_in_table] = var_ave

            toc = time.time()
            print('Time to process polygon=',toc-tic)
        dat.close() 
fire_features

['APCP_P8_L1_GST0_acc']
442
2019-02-17
2019 02 17
/data2/lthapa/2019/STAGEIV/ST4.2019021712.24h.nc
(array([258, 259]), array([176, 176]))
0.0
Time to process polygon= 0.7909574508666992
2019-02-18
2019 02 18
/data2/lthapa/2019/STAGEIV/ST4.2019021812.24h.nc
(array([258, 259]), array([176, 176]))
0.0
Time to process polygon= 0.8308413028717041
2019-02-18
2019 02 18
/data2/lthapa/2019/STAGEIV/ST4.2019021812.24h.nc
(array([258, 259]), array([176, 176]))
0.0
Time to process polygon= 0.7975642681121826
2019-02-19
2019 02 19
/data2/lthapa/2019/STAGEIV/ST4.2019021912.24h.nc
(array([258, 259]), array([176, 176]))
0.0
Time to process polygon= 0.8315963745117188
2019-02-24
2019 02 24
/data2/lthapa/2019/STAGEIV/ST4.2019022412.24h.nc
(array([454, 455]), array([411, 411]))
0.0
Time to process polygon= 0.5205152034759521
2019-02-25
2019 02 25
/data2/lthapa/2019/STAGEIV/ST4.2019022512.24h.nc
(array([454, 455]), array([411, 411]))
0.0
Time to process polygon= 0.5205020904541016
2019-03-06
2019 03 06
/d

(array([638, 638]), array([199, 200]))
0.0
Time to process polygon= 0.5761942863464355
(array([349, 350]), array([220, 220]))
9.721666340542304
Time to process polygon= 0.691162109375
2019-05-08
2019 05 08
/data2/lthapa/2019/STAGEIV/ST4.2019050812.24h.nc
(array([556]), array([71]))
0.0
Time to process polygon= 0.7081582546234131
(array([638, 638]), array([199, 200]))
0.0
Time to process polygon= 0.5657958984375
2019-05-09
2019 05 09
/data2/lthapa/2019/STAGEIV/ST4.2019050912.24h.nc
(array([556]), array([71]))
0.0
Time to process polygon= 0.7198705673217773
(array([638, 638]), array([199, 200]))
0.0
Time to process polygon= 0.5647296905517578
2019-05-09
2019 05 09
/data2/lthapa/2019/STAGEIV/ST4.2019050912.24h.nc
(array([556]), array([71]))
0.0
Time to process polygon= 0.6999368667602539
2019-05-10
2019 05 10
/data2/lthapa/2019/STAGEIV/ST4.2019051012.24h.nc
(array([556]), array([71]))
0.0
Time to process polygon= 0.7002279758453369
2019-05-14
2019 05 14
/data2/lthapa/2019/STAGEIV/ST4.2019

(array([268]), array([303]))
0.0
Time to process polygon= 0.6774575710296631
2019-06-02
2019 06 02
/data2/lthapa/2019/STAGEIV/ST4.2019060212.24h.nc
(array([316, 316, 317, 317, 318]), array([255, 256, 255, 256, 255]))
0.0
Time to process polygon= 0.7007267475128174
(array([294]), array([255]))
0.0
Time to process polygon= 0.6987583637237549
(array([268]), array([303]))
0.0
Time to process polygon= 0.6618335247039795
2019-06-03
2019 06 03
/data2/lthapa/2019/STAGEIV/ST4.2019060312.24h.nc
(array([316, 316, 317, 317, 318]), array([255, 256, 255, 256, 255]))
0.0
Time to process polygon= 0.698636531829834
(array([294]), array([255]))
0.0
Time to process polygon= 0.6944210529327393
(array([268]), array([303]))
0.0
Time to process polygon= 0.6611039638519287
2019-06-03
2019 06 03
/data2/lthapa/2019/STAGEIV/ST4.2019060312.24h.nc
(array([315, 316, 316, 317, 317, 318]), array([255, 255, 256, 255, 256, 255]))
0.0
Time to process polygon= 0.6973543167114258
(array([294, 294, 295, 295]), array([255, 

(array([268, 268]), array([302, 303]))
0.0
Time to process polygon= 0.6842124462127686
(array([260]), array([332]))
0.0
Time to process polygon= 0.6551847457885742
(array([255]), array([323]))
0.0
Time to process polygon= 0.6615045070648193
2019-06-09
2019 06 09
/data2/lthapa/2019/STAGEIV/ST4.2019060912.24h.nc
(array([317, 317, 318]), array([255, 256, 255]))
0.0
Time to process polygon= 0.6779520511627197
(array([274]), array([324]))
0.0
Time to process polygon= 0.6335160732269287
(array([293, 293, 294, 294, 295, 295]), array([255, 256, 255, 256, 255, 256]))
0.0
Time to process polygon= 0.699760913848877
(array([411, 411, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446,
       447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459,
       460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472,
       473]), array([56, 57,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       

(array([364, 364, 365, 365, 390, 391, 392, 393, 394, 395, 396, 397, 398,
       399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411,
       412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424,
       425, 426, 427, 428]), array([59, 60, 59, 60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0]))
0.0
Time to process polygon= 0.8376719951629639
(array([380, 380]), array([396, 397]))
0.0
Time to process polygon= 0.5588316917419434
(array([367]), array([339]))
0.0
Time to process polygon= 0.5659515857696533
(array([263, 263, 264, 264, 265]), array([253, 254, 253, 254, 254]))
0.0
Time to process polygon= 0.7336568832397461
(array([268, 268]), array([302, 303]))
0.0
Time to process polygon= 0.6725494861602783
(array([367, 368]), array([108, 108]))
0.0
Time to process polygon= 0.7710208892822266
2019-06-13
2019 06 13
/data2/lthapa/2019/STAGEIV/ST4.201

(array([367, 368]), array([108, 108]))
0.0
Time to process polygon= 0.7671945095062256
(array([542]), array([101]))
0.0
Time to process polygon= 0.672715425491333
2019-06-17
2019 06 17
/data2/lthapa/2019/STAGEIV/ST4.2019061712.24h.nc
(array([267]), array([382]))
0.5
Time to process polygon= 0.6239898204803467
(array([292, 292, 293, 293, 294, 294]), array([254, 255, 254, 255, 254, 255]))
0.0
Time to process polygon= 0.729412317276001
(array([380, 380]), array([396, 397]))
1.299533464677822
Time to process polygon= 0.5487196445465088
(array([262, 262, 263, 263, 263, 263, 264, 264, 264, 264, 264, 265, 265,
       265, 265, 265, 266, 266, 266, 266, 267, 267, 267]), array([253, 254, 252, 253, 254, 255, 251, 252, 253, 254, 255, 251, 252,
       253, 254, 255, 251, 252, 253, 254, 251, 252, 253]))
0.0
Time to process polygon= 0.7827053070068359
(array([367, 368]), array([108, 108]))
0.0
Time to process polygon= 0.7687594890594482
(array([542]), array([101]))
0.0
Time to process polygon= 0.6755

(array([261, 262]), array([394, 394]))
0.0
Time to process polygon= 0.6227490901947021
(array([316]), array([347]))
0.0
Time to process polygon= 0.5960512161254883
2019-06-21
2019 06 21
/data2/lthapa/2019/STAGEIV/ST4.2019062112.24h.nc
(array([267]), array([382]))
0.0
Time to process polygon= 0.6125454902648926
(array([495, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538,
       539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551,
       552, 553, 554, 555, 556]), array([39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0]))
0.0
Time to process polygon= 0.6480128765106201
(array([380, 380]), array([396, 397]))
0.0
Time to process polygon= 0.546905517578125
(array([642, 643, 644]), array([143, 143, 143]))
0.0
Time to process polygon= 0.6340892314910889
(array(

(array([342]), array([371]))
1.100000023841858
Time to process polygon= 0.5752866268157959
(array([261, 261, 262, 262, 262, 263, 263]), array([393, 394, 393, 394, 395, 393, 394]))
0.0
Time to process polygon= 0.6373188495635986
(array([316]), array([347]))
0.0
Time to process polygon= 0.6028869152069092
2019-06-24
2019 06 24
/data2/lthapa/2019/STAGEIV/ST4.2019062412.24h.nc
(array([267]), array([382]))
0.0
Time to process polygon= 0.6152257919311523
(array([495, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538,
       539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551,
       552, 553, 554, 555, 556]), array([39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0]))
0.0
Time to process polygon= 0.64841628074646
(array([380, 380]), array([396, 397]))
0.0
Time to 

(array([261, 261, 261, 262, 262, 262, 263, 263]), array([393, 394, 395, 392, 393, 394, 393, 394]))
0.0
Time to process polygon= 0.6611242294311523
(array([316]), array([347]))
0.0
Time to process polygon= 0.6168427467346191
2019-06-27
2019 06 27
/data2/lthapa/2019/STAGEIV/ST4.2019062712.24h.nc
(array([267]), array([382]))
3.0999999046325684
Time to process polygon= 0.6303796768188477
(array([399, 400, 400, 401]), array([242, 241, 242, 241]))
0.0
Time to process polygon= 0.6678190231323242
(array([380, 380]), array([396, 397]))
0.0
Time to process polygon= 0.5583159923553467
(array([434]), array([96]))
0.0
Time to process polygon= 0.7382979393005371
(array([377, 378, 378, 379, 379]), array([321, 320, 321, 320, 321]))
0.0
Time to process polygon= 0.6030125617980957
(array([266, 266, 266, 266, 267, 267, 267, 267, 267, 267]), array([253, 254, 255, 256, 252, 253, 254, 255, 256, 257]))
0.0
Time to process polygon= 0.7419164180755615
(array([417, 417, 442, 443, 444, 445, 446, 447, 448, 449, 4

(array([203, 204]), array([301, 301]))
0.0
Time to process polygon= 0.7022781372070312
2019-07-01
2019 07 01
/data2/lthapa/2019/STAGEIV/ST4.2019070112.24h.nc
(array([266, 267, 267]), array([383, 382, 383]))
0.0
Time to process polygon= 0.6395208835601807
(array([400, 400]), array([241, 242]))
0.0
Time to process polygon= 0.6395084857940674
(array([380, 380]), array([396, 397]))
1.4017695805065407
Time to process polygon= 0.5474011898040771
(array([434]), array([96]))
0.0
Time to process polygon= 0.7428903579711914
(array([377, 378, 378]), array([321, 321, 322]))
0.0
Time to process polygon= 0.6017966270446777
(array([451]), array([388]))
7.0
Time to process polygon= 0.5409679412841797
(array([261, 261, 262]), array([393, 394, 393]))
0.0
Time to process polygon= 0.6372637748718262
(array([250, 251]), array([336, 336]))
0.0
Time to process polygon= 0.650843620300293
(array([203, 204]), array([301, 301]))
0.0
Time to process polygon= 0.7195706367492676
2019-07-02
2019 07 02
/data2/lthapa/

(array([268, 268]), array([304, 305]))
0.0
Time to process polygon= 0.6719398498535156
(array([281]), array([294]))
0.0
Time to process polygon= 0.6663370132446289
(array([252, 252, 253, 253]), array([329, 330, 329, 330]))
0.0
Time to process polygon= 0.655085563659668
(array([269, 269]), array([301, 302]))
0.0
Time to process polygon= 0.6786208152770996
2019-07-05
2019 07 05
/data2/lthapa/2019/STAGEIV/ST4.2019070512.24h.nc
(array([443]), array([269]))
0.0
Time to process polygon= 0.6198508739471436
(array([400, 400]), array([241, 242]))
0.0
Time to process polygon= 0.6619577407836914
(array([252, 252, 253, 253]), array([316, 317, 316, 317]))
0.0
Time to process polygon= 0.6976959705352783
(array([252, 252, 253, 253]), array([316, 317, 316, 317]))
0.0
Time to process polygon= 0.6865689754486084
(array([380, 380]), array([396, 397]))
0.0
Time to process polygon= 0.5454561710357666
(array([434]), array([96]))
0.0
Time to process polygon= 0.7562124729156494
(array([394, 394]), array([402,

(array([451]), array([388]))
1.1299999952316284
Time to process polygon= 0.5526013374328613
(array([612]), array([226]))
0.7550720267799451
Time to process polygon= 0.6074790954589844
(array([527, 527]), array([245, 246]))
0.0
Time to process polygon= 0.5828204154968262
(array([578, 579]), array([138, 138]))
0.0
Time to process polygon= 0.6428985595703125
(array([250, 250, 251, 251]), array([331, 332, 331, 332]))
4.535743497721185
Time to process polygon= 0.6912539005279541
(array([268, 268]), array([304, 305]))
7.5059786522686505
Time to process polygon= 0.6984710693359375
(array([281, 281]), array([294, 295]))
1.4979982024726737
Time to process polygon= 0.6971876621246338
(array([252, 252, 253, 253]), array([329, 330, 329, 330]))
4.537084547014958
Time to process polygon= 0.6709990501403809
2019-07-08
2019 07 08
/data2/lthapa/2019/STAGEIV/ST4.2019070812.24h.nc
(array([332, 333]), array([357, 357]))
0.0
Time to process polygon= 0.6376945972442627
(array([400]), array([242]))
0.0
Time 

(array([281, 281]), array([294, 295]))
0.7993381758041886
Time to process polygon= 0.6728494167327881
(array([252, 252, 253, 253]), array([329, 330, 329, 330]))
1.4705427655408398
Time to process polygon= 0.6741588115692139
2019-07-12
2019 07 12
/data2/lthapa/2019/STAGEIV/ST4.2019071212.24h.nc
(array([332, 333]), array([357, 357]))
0.17461407205658286
Time to process polygon= 0.6094274520874023
(array([262]), array([330]))
0.0
Time to process polygon= 0.6395919322967529
(array([250, 250, 251, 251]), array([332, 333, 332, 333]))
0.5656530781261121
Time to process polygon= 0.6581759452819824
(array([380, 380]), array([396, 397]))
2.948219235570217
Time to process polygon= 0.5503382682800293
(array([434]), array([96]))
0.0
Time to process polygon= 0.7585229873657227
(array([569, 569]), array([217, 218]))
0.0
Time to process polygon= 0.5775811672210693
(array([373, 374]), array([247, 247]))
0.270832557562821
Time to process polygon= 0.647758960723877
(array([451]), array([388]))
0.0
Time t

(array([281, 281]), array([294, 295]))
0.0
Time to process polygon= 0.6725137233734131
(array([252, 252, 253, 253]), array([329, 330, 329, 330]))
0.5367743318492406
Time to process polygon= 0.6610565185546875
2019-07-15
2019 07 15
/data2/lthapa/2019/STAGEIV/ST4.2019071512.24h.nc
(array([340]), array([373]))
15.300000190734863
Time to process polygon= 0.6094253063201904
(array([563, 563]), array([212, 213]))
0.0
Time to process polygon= 0.5757646560668945
(array([470, 470]), array([160, 161]))
0.0
Time to process polygon= 0.6706099510192871
(array([262, 262, 263]), array([343, 344, 343]))
1.9515627981149841
Time to process polygon= 0.6300106048583984
(array([643]), array([145]))
0.0
Time to process polygon= 0.5856714248657227
(array([250, 250, 251]), array([332, 333, 332]))
1.2875825147590252
Time to process polygon= 0.6573472023010254
(array([309, 310]), array([252, 252]))
0.5700260997692972
Time to process polygon= 0.6845297813415527
(array([569, 569, 570, 570]), array([217, 218, 217,

(array([295]), array([258]))
0.0
Time to process polygon= 0.6816606521606445
(array([309, 310, 310]), array([252, 252, 253]))
0.0
Time to process polygon= 0.7083902359008789
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5821409225463867
(array([299, 299, 300]), array([258, 259, 259]))
0.0
Time to process polygon= 0.6872870922088623
(array([352]), array([241]))
0.0
Time to process polygon= 0.6779093742370605
(array([612]), array([226]))
0.0
Time to process polygon= 0.5497190952301025
(array([284]), array([272]))
0.0
Time to process polygon= 0.6832199096679688
(array([249]), array([329]))
2.5
Time to process polygon= 0.6663038730621338
(array([490, 491, 491, 492, 492]), array([259, 258, 259, 258, 259]))
0.0
Time to process polygon= 0.595081090927124
(array([281, 281]), array([294, 295]))
0.4995863524332011
Time to process polygon= 0.6762862205505371
(array([253]), array([287]))
1.5
Time to process polygon= 0.6957135200500488
(array([252, 252, 2

(array([366]), array([340]))
0.0
Time to process polygon= 0.5794401168823242
(array([339, 339, 340, 340]), array([373, 374, 373, 374]))
0.0
Time to process polygon= 0.5835928916931152
(array([291]), array([229]))
0.0
Time to process polygon= 0.7131509780883789
(array([563, 563]), array([212, 213]))
0.0
Time to process polygon= 0.5753676891326904
(array([262, 262, 263, 263]), array([343, 344, 343, 344]))
3.895078411655467
Time to process polygon= 0.6518490314483643
(array([250, 250, 251]), array([332, 333, 332]))
2.9459946341072865
Time to process polygon= 0.6591684818267822
(array([261]), array([280]))
0.30000001192092896
Time to process polygon= 0.6930134296417236
(array([379]), array([296]))
0.0
Time to process polygon= 0.6078746318817139
(array([294, 294, 295, 295]), array([258, 259, 258, 259]))
0.0
Time to process polygon= 0.6973755359649658
(array([437]), array([334]))
0.0
Time to process polygon= 0.5369064807891846
(array([309, 309, 310, 310, 311]), array([251, 252, 251, 252, 252

(array([623, 624]), array([134, 134]))
0.0
Time to process polygon= 0.6066029071807861
(array([379]), array([296]))
0.0
Time to process polygon= 0.6107668876647949
(array([293, 294, 294, 295, 295]), array([259, 258, 259, 258, 259]))
0.0
Time to process polygon= 0.6986675262451172
(array([563]), array([212]))
0.0
Time to process polygon= 0.5658581256866455
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5704977512359619
(array([299, 299]), array([258, 259]))
0.0
Time to process polygon= 0.693972110748291
(array([352, 353]), array([241, 241]))
0.0
Time to process polygon= 0.666273832321167
(array([612]), array([226]))
0.0
Time to process polygon= 0.5400369167327881
(array([284, 285, 285]), array([272, 271, 272]))
0.0
Time to process polygon= 0.6835625171661377
2019-07-22
2019 07 22
/data2/lthapa/2019/STAGEIV/ST4.2019072212.24h.nc
(array([366]), array([340]))
0.0
Time to process polygon= 0.5912823677062988
(array([563]), array([212]))
0.0
Time to 

(array([640]), array([241]))
0.25
Time to process polygon= 0.649583101272583
(array([644]), array([145]))
0.25
Time to process polygon= 0.5953726768493652
(array([465, 466]), array([150, 150]))
0.30000001192092896
Time to process polygon= 0.6714258193969727
(array([647, 648]), array([135, 135]))
1.2109023150032832
Time to process polygon= 0.6087489128112793
(array([651]), array([186]))
4.829999923706055
Time to process polygon= 0.5511279106140137
(array([630, 630]), array([127, 128]))
0.26144580650036686
Time to process polygon= 0.6913104057312012
(array([621, 621]), array([120, 121]))
0.0
Time to process polygon= 0.9087510108947754
(array([379]), array([296]))
0.0
Time to process polygon= 0.7004821300506592
(array([294]), array([259]))
6.300000190734863
Time to process polygon= 0.6885790824890137
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5760965347290039
(array([352, 353]), array([241, 241]))
1.0848996281689225
Time to process polygon= 0

(array([315, 315, 315, 315, 316, 316, 316]), array([250, 251, 252, 253, 250, 251, 252]))
0.0
Time to process polygon= 0.726581335067749
(array([640, 640, 641, 641]), array([241, 242, 241, 242]))
0.0
Time to process polygon= 0.5230906009674072
(array([630]), array([127]))
0.0
Time to process polygon= 0.6084952354431152
(array([670]), array([135]))
0.0
Time to process polygon= 0.5778858661651611
(array([379]), array([296]))
0.5
Time to process polygon= 0.6046442985534668
(array([293, 293, 294, 294]), array([258, 259, 258, 259]))
3.7358969064523615
Time to process polygon= 0.6993422508239746
(array([570, 570]), array([217, 218]))
0.0
Time to process polygon= 0.5776822566986084
(array([351, 351, 352, 353]), array([241, 242, 241, 241]))
0.286392728049641
Time to process polygon= 0.6940243244171143
(array([612]), array([226]))
0.0
Time to process polygon= 0.5436198711395264
(array([359]), array([347]))
0.800000011920929
Time to process polygon= 0.8625631332397461
(array([627]), array([248]))

(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5819039344787598
(array([351, 352, 352, 353, 353, 353, 354, 354]), array([241, 240, 241, 239, 240, 241, 239, 240]))
0.0
Time to process polygon= 0.6989781856536865
(array([617]), array([234]))
0.0
Time to process polygon= 0.5266084671020508
(array([617, 617, 618, 618]), array([279, 280, 279, 280]))
0.0
Time to process polygon= 0.5126032829284668
(array([612]), array([226]))
0.0
Time to process polygon= 0.5444235801696777
(array([382]), array([297]))
0.0
Time to process polygon= 0.608196496963501
(array([359]), array([347]))
0.0
Time to process polygon= 0.614717960357666
(array([627]), array([248]))
0.0
Time to process polygon= 0.6638922691345215
(array([652, 652, 653]), array([128, 129, 128]))
0.0
Time to process polygon= 0.7143914699554443
(array([670]), array([135]))
0.0
Time to process polygon= 0.5802621841430664
(array([564, 564, 565, 565, 565, 566, 566, 566, 567]), array([57, 58, 57, 58, 59, 

(array([627]), array([248]))
0.0
Time to process polygon= 0.695366621017456
(array([652, 652, 653]), array([128, 129, 128]))
0.0
Time to process polygon= 0.7112326622009277
(array([670]), array([135]))
0.0
Time to process polygon= 0.5825097560882568
(array([564, 564, 565, 565, 565, 566, 566, 566]), array([57, 58, 57, 58, 59, 57, 58, 59]))
0.0
Time to process polygon= 0.735903263092041
2019-07-31
2019 07 31
/data2/lthapa/2019/STAGEIV/ST4.2019073112.24h.nc
(array([315, 315, 315, 315, 316, 316, 316]), array([250, 251, 252, 253, 250, 251, 252]))
12.104162549574148
Time to process polygon= 0.7248389720916748
(array([640, 640, 641, 641]), array([241, 242, 241, 242]))
0.0
Time to process polygon= 0.5252952575683594
(array([431]), array([271]))
0.0
Time to process polygon= 0.5937275886535645
(array([670]), array([135]))
0.0
Time to process polygon= 0.5832736492156982
(array([392, 392]), array([265, 266]))
0.0
Time to process polygon= 0.8869259357452393
(array([284]), array([282]))
1.7999999523

(array([320]), array([364]))
16.399999618530273
Time to process polygon= 0.5807650089263916
(array([448, 449]), array([266, 266]))
5.067098505614705
Time to process polygon= 0.6220636367797852
(array([627]), array([248]))
0.0
Time to process polygon= 0.516416072845459
(array([652, 652, 653, 653]), array([128, 129, 128, 129]))
0.0
Time to process polygon= 0.6096460819244385
(array([670]), array([135]))
0.0
Time to process polygon= 0.5802021026611328
(array([564, 565, 566, 566]), array([58, 58, 57, 58]))
0.0
Time to process polygon= 0.7165863513946533
2019-08-01
2019 08 01
/data2/lthapa/2019/STAGEIV/ST4.2019080112.24h.nc
(array([315, 315, 315, 315, 316, 316, 316]), array([250, 251, 252, 253, 250, 251, 252]))
0.47929054365000934
Time to process polygon= 0.7144324779510498
(array([431]), array([271]))
7.099999904632568
Time to process polygon= 0.5951392650604248
(array([670]), array([135]))
0.0
Time to process polygon= 0.5910975933074951
(array([392, 392]), array([265, 266]))
0.29387379268

(array([320]), array([364]))
0.0
Time to process polygon= 0.5821382999420166
(array([627]), array([248]))
0.0
Time to process polygon= 0.5104508399963379
(array([670]), array([135]))
0.0
Time to process polygon= 0.5868022441864014
(array([557]), array([61]))
0.0
Time to process polygon= 0.7101054191589355
(array([566, 566, 567]), array([57, 58, 57]))
0.0
Time to process polygon= 0.7174034118652344
(array([531, 532, 532, 533, 533, 534]), array([235, 234, 235, 234, 235, 234]))
0.0
Time to process polygon= 0.6241044998168945
2019-08-03
2019 08 03
/data2/lthapa/2019/STAGEIV/ST4.2019080312.24h.nc
(array([315, 315, 315, 315, 316, 316, 316]), array([250, 251, 252, 253, 250, 251, 252]))
0.15463925949820986
Time to process polygon= 0.7189822196960449
(array([431]), array([271]))
0.0
Time to process polygon= 0.5994293689727783
(array([670]), array([135]))
0.0
Time to process polygon= 0.6005232334136963
(array([392, 392]), array([265, 266]))
0.05082290168381905
Time to process polygon= 0.93178510

(array([617]), array([234]))
0.0
Time to process polygon= 0.5360147953033447
(array([612]), array([226]))
0.0
Time to process polygon= 0.5434167385101318
(array([381, 382]), array([297, 297]))
3.9346365590904444
Time to process polygon= 0.6232473850250244
(array([413]), array([106]))
0.0
Time to process polygon= 0.7402522563934326
(array([320]), array([364]))
5.900000095367432
Time to process polygon= 0.5769894123077393
(array([627]), array([248]))
0.0
Time to process polygon= 0.5212228298187256
(array([670]), array([135]))
0.0
Time to process polygon= 0.5884835720062256
(array([557, 558]), array([61, 61]))
0.0
Time to process polygon= 0.7053184509277344
2019-08-04
2019 08 04
/data2/lthapa/2019/STAGEIV/ST4.2019080412.24h.nc
(array([315, 315, 315, 315, 316, 316, 316]), array([250, 251, 252, 253, 250, 251, 252]))
7.239063121488046
Time to process polygon= 0.7168877124786377
(array([588]), array([231]))
0.0
Time to process polygon= 0.55381178855896
(array([438]), array([258]))
0.0
Time to

(array([471, 471, 472, 472, 473]), array([209, 210, 209, 210, 210]))
0.0
Time to process polygon= 0.6372263431549072
(array([462, 462, 463, 463, 463, 464, 464]), array([186, 187, 186, 187, 188, 187, 188]))
0.0
Time to process polygon= 0.6683444976806641
(array([436, 436, 437, 437]), array([93, 94, 93, 94]))
0.0
Time to process polygon= 0.7795705795288086
(array([488, 489]), array([230, 230]))
0.0
Time to process polygon= 0.5970313549041748
(array([594, 595]), array([178, 178]))
0.07694510407824945
Time to process polygon= 0.587409496307373
(array([500, 501, 501, 501, 502]), array([222, 221, 222, 223, 222]))
0.0
Time to process polygon= 0.6132667064666748
(array([273, 273]), array([246, 247]))
0.0
Time to process polygon= 0.7106611728668213
(array([590]), array([205]))
0.0
Time to process polygon= 0.5613937377929688
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5771095752716064
(array([492, 492, 493, 493, 493, 494, 494]), array([245, 246, 244,

(array([352, 352, 353]), array([239, 240, 239]))
2.968063048540796
Time to process polygon= 0.6758348941802979
(array([347, 347, 348]), array([239, 240, 239]))
1.809794684866077
Time to process polygon= 0.7125747203826904
(array([617]), array([234]))
0.0
Time to process polygon= 0.5406856536865234
(array([369]), array([110]))
0.0
Time to process polygon= 0.8154959678649902
(array([612]), array([226]))
0.0
Time to process polygon= 0.5419363975524902
(array([381]), array([297]))
0.0
Time to process polygon= 0.6052930355072021
(array([413, 414]), array([106, 106]))
0.0
Time to process polygon= 0.7368905544281006
(array([320]), array([364]))
0.30000001192092896
Time to process polygon= 0.5859489440917969
(array([627]), array([248]))
0.0
Time to process polygon= 0.5073697566986084
(array([670]), array([135]))
0.0
Time to process polygon= 0.5812585353851318
2019-08-07
2019 08 07
/data2/lthapa/2019/STAGEIV/ST4.2019080712.24h.nc
(array([315, 315, 315, 315, 316, 316, 316]), array([250, 251, 252

(array([485, 485, 486]), array([239, 240, 239]))
0.0
Time to process polygon= 0.595534086227417
(array([623, 623, 624]), array([272, 273, 272]))
0.0
Time to process polygon= 0.5028736591339111
(array([359, 360]), array([347, 347]))
0.0
Time to process polygon= 0.5731637477874756
(array([462, 462, 463, 463, 464, 464, 465, 465]), array([187, 188, 187, 188, 187, 188, 187, 188]))
0.0
Time to process polygon= 0.6776752471923828
(array([436, 436, 437, 437]), array([93, 94, 93, 94]))
0.0
Time to process polygon= 0.7782840728759766
(array([594, 595]), array([178, 178]))
0.3048815126894263
Time to process polygon= 0.5937716960906982
(array([590, 591]), array([205, 205]))
0.0
Time to process polygon= 0.5709657669067383
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5765523910522461
(array([649]), array([209]))
0.0
Time to process polygon= 0.5310680866241455
(array([352, 352, 353]), array([239, 240, 239]))
6.920089645589842
Time to process polygon= 0.674

(array([588, 588, 588]), array([230, 231, 232]))
0.0
Time to process polygon= 0.5619895458221436
(array([265]), array([320]))
2.4000000953674316
Time to process polygon= 0.6518840789794922
(array([644, 644]), array([258, 259]))
0.0
Time to process polygon= 0.511211633682251
(array([431]), array([271]))
1.0
Time to process polygon= 0.5916552543640137
(array([670]), array([135]))
0.0
Time to process polygon= 0.5799446105957031
(array([392]), array([266]))
1.0
Time to process polygon= 0.6275591850280762
(array([683, 683, 684, 684]), array([141, 142, 141, 142]))
0.0
Time to process polygon= 0.5855696201324463
(array([378]), array([295]))
0.0
Time to process polygon= 0.6198742389678955
(array([665, 665, 665, 665, 666, 666, 666, 666, 667, 667, 667, 667, 668,
       668, 668, 669, 669, 669]), array([175, 176, 177, 178, 175, 176, 177, 178, 175, 176, 177, 178, 175,
       176, 177, 175, 176, 177]))
0.0
Time to process polygon= 0.619497537612915
(array([351, 352]), array([221, 221]))
0.0
Time to

(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
4.753643670770557
Time to process polygon= 0.5760667324066162
(array([352, 352, 353, 353]), array([239, 240, 239, 240]))
1.1559835829326572
Time to process polygon= 0.6746916770935059
(array([347, 347, 348]), array([239, 240, 239]))
3.673691758541721
Time to process polygon= 0.716080904006958
(array([617]), array([234]))
0.25
Time to process polygon= 0.5233116149902344
(array([369]), array([110]))
0.0
Time to process polygon= 0.7524971961975098
(array([612]), array([226]))
1.7799999713897705
Time to process polygon= 0.5426511764526367
(array([381]), array([297]))
0.0
Time to process polygon= 0.5986473560333252
(array([413, 414]), array([106, 106]))
0.0
Time to process polygon= 0.7586908340454102
(array([320]), array([364]))
1.0
Time to process polygon= 0.584282636642456
(array([670]), array([135]))
16.0
Time to process polygon= 0.5791459083557129
(array([681, 681, 682]), array([192, 193, 192]))
0.5446982511378147
Time to proces

(array([633, 634, 634]), array([346, 346, 347]))
9.958294869206737
Time to process polygon= 0.44943690299987793
(array([225, 225]), array([404, 405]))
3.8926297775942094
Time to process polygon= 0.6465933322906494
(array([590, 591]), array([212, 212]))
3.5558550715479855
Time to process polygon= 0.5962953567504883
2019-08-12
2019 08 12
/data2/lthapa/2019/STAGEIV/ST4.2019081212.24h.nc
(array([315, 315, 315, 315, 316, 316, 316]), array([250, 251, 252, 253, 250, 251, 252]))
0.0
Time to process polygon= 0.7232069969177246
(array([588, 588, 588]), array([230, 231, 232]))
2.3104549656386686
Time to process polygon= 0.5662083625793457
(array([265]), array([320]))
0.0
Time to process polygon= 0.6496896743774414
(array([644, 644]), array([258, 259]))
11.796919454175201
Time to process polygon= 0.5118153095245361
(array([431]), array([271]))
0.0
Time to process polygon= 0.5928771495819092
(array([670]), array([135]))
0.0
Time to process polygon= 0.5794239044189453
(array([683, 683, 684, 684]), a

(array([351, 352]), array([221, 221]))
0.0
Time to process polygon= 0.6894114017486572
(array([599, 599, 600, 600]), array([142, 143, 142, 143]))
0.0
Time to process polygon= 0.630969762802124
(array([320, 321]), array([242, 242]))
0.0
Time to process polygon= 0.6946506500244141
(array([304, 305]), array([225, 225]))
0.0
Time to process polygon= 0.7118737697601318
(array([381]), array([301]))
0.0
Time to process polygon= 0.6019017696380615
(array([359, 360]), array([347, 347]))
0.0
Time to process polygon= 0.578545093536377
(array([310]), array([243]))
0.0
Time to process polygon= 0.6990222930908203
(array([436, 436, 437, 437]), array([93, 94, 93, 94]))
0.0
Time to process polygon= 0.7892951965332031
(array([594, 595]), array([178, 178]))
0.0
Time to process polygon= 0.6004254817962646
(array([590, 591, 591]), array([206, 205, 206]))
0.0
Time to process polygon= 0.5787017345428467
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.588674783706665


(array([320, 321]), array([242, 242]))
0.0
Time to process polygon= 0.6854801177978516
(array([304, 305]), array([225, 225]))
0.0
Time to process polygon= 0.6989543437957764
(array([359, 360]), array([347, 347]))
0.0
Time to process polygon= 0.5782046318054199
(array([310]), array([243]))
0.0
Time to process polygon= 0.6979587078094482
(array([436, 436, 437, 437]), array([93, 94, 93, 94]))
0.0
Time to process polygon= 0.7903487682342529
(array([594, 595]), array([178, 178]))
0.0
Time to process polygon= 0.5976965427398682
(array([590, 591, 591]), array([206, 205, 206]))
0.0
Time to process polygon= 0.5877153873443604
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5893247127532959
(array([337]), array([360]))
0.4000000059604645
Time to process polygon= 0.5786981582641602
(array([351, 351, 352, 352, 352, 353, 353]), array([240, 241, 239, 240, 241, 239, 240]))
0.0
Time to process polygon= 0.690314769744873
(array([347]), array([239]))
0.0
Time to

(array([369]), array([110]))
0.0
Time to process polygon= 0.7586896419525146
(array([612]), array([226]))
0.0
Time to process polygon= 0.5418565273284912
(array([381]), array([297]))
0.0
Time to process polygon= 0.6001546382904053
(array([412, 413, 414]), array([106, 106, 106]))
0.0
Time to process polygon= 0.7588808536529541
(array([629, 629, 630]), array([349, 350, 349]))
4.0437623606567055
Time to process polygon= 0.4321446418762207
(array([603, 604]), array([116, 116]))
0.0
Time to process polygon= 0.6337766647338867
(array([320]), array([364]))
3.9000000953674316
Time to process polygon= 0.586705207824707
(array([670]), array([135]))
0.0
Time to process polygon= 0.5771093368530273
(array([633, 634, 634]), array([346, 346, 347]))
3.4119326782096886
Time to process polygon= 0.44132304191589355
(array([225, 225]), array([404, 405]))
7.947333465656007
Time to process polygon= 0.6340038776397705
(array([590, 591]), array([212, 212]))
0.0
Time to process polygon= 0.5942246913909912
2019

(array([644, 644]), array([258, 259]))
0.0
Time to process polygon= 0.5141842365264893
(array([431]), array([271]))
0.0
Time to process polygon= 0.5903820991516113
(array([571, 571, 572]), array([372, 373, 372]))
0.8963049919296975
Time to process polygon= 0.47627854347229004
(array([670]), array([135]))
0.0
Time to process polygon= 0.5782279968261719
(array([460]), array([132]))
0.0
Time to process polygon= 0.6941802501678467
(array([683, 683, 684, 684]), array([141, 142, 141, 142]))
0.0
Time to process polygon= 0.573997974395752
(array([378]), array([295]))
0.0
Time to process polygon= 0.6061348915100098
(array([665, 665, 665, 665, 666, 666, 666, 666, 667, 667, 667, 667, 668,
       668, 668, 669, 669, 669]), array([175, 176, 177, 178, 175, 176, 177, 178, 175, 176, 177, 178, 175,
       176, 177, 175, 176, 177]))
0.0
Time to process polygon= 0.6006269454956055
(array([365, 365, 366, 366]), array([110, 111, 110, 111]))
0.0
Time to process polygon= 0.8132624626159668
(array([351, 352])

(array([304, 305]), array([220, 220]))
0.0
Time to process polygon= 0.7150208950042725
(array([381]), array([243]))
0.0
Time to process polygon= 0.6430842876434326
(array([310, 310]), array([243, 244]))
0.0
Time to process polygon= 0.6926829814910889
(array([436, 436, 437, 437]), array([93, 94, 93, 94]))
0.0
Time to process polygon= 0.7800664901733398
(array([594, 594, 595, 595]), array([177, 178, 177, 178]))
0.0
Time to process polygon= 0.5909957885742188
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5771088600158691
(array([337]), array([360]))
0.30000001192092896
Time to process polygon= 0.5799775123596191
(array([351, 351, 352, 352, 352, 353, 353, 354]), array([240, 241, 239, 240, 241, 239, 240, 239]))
0.0
Time to process polygon= 0.6992185115814209
(array([347, 347, 348, 348]), array([239, 240, 239, 240]))
0.0
Time to process polygon= 0.6879007816314697
(array([617]), array([234]))
0.0
Time to process polygon= 0.5264072418212891
(array([

(array([514]), array([310]))
0.0
Time to process polygon= 0.5128521919250488
(array([571]), array([372]))
0.0
Time to process polygon= 0.4494760036468506
(array([444, 445]), array([350, 350]))
0.0
Time to process polygon= 0.524644136428833
(array([670]), array([135]))
0.0
Time to process polygon= 0.5765855312347412
(array([683, 683, 684, 684]), array([141, 142, 141, 142]))
0.0
Time to process polygon= 0.573596715927124
(array([378]), array([295]))
0.0
Time to process polygon= 0.6056756973266602
(array([665, 665, 665, 665, 666, 666, 666, 666, 667, 667, 667, 667, 668,
       668, 668, 669, 669, 669]), array([175, 176, 177, 178, 175, 176, 177, 178, 175, 176, 177, 178, 175,
       176, 177, 175, 176, 177]))
0.0
Time to process polygon= 0.6017622947692871
(array([365, 365, 366]), array([110, 111, 111]))
0.0
Time to process polygon= 0.7675778865814209
(array([351, 351, 352]), array([221, 222, 221]))
0.0
Time to process polygon= 0.6926796436309814
(array([599, 599, 600, 600]), array([142, 143

(array([588, 589]), array([231, 231]))
0.0
Time to process polygon= 0.5499331951141357
(array([644, 644]), array([258, 259]))
0.0
Time to process polygon= 0.5092582702636719
(array([431]), array([271]))
0.0
Time to process polygon= 0.591254472732544
(array([571]), array([372]))
0.0
Time to process polygon= 0.44791293144226074
(array([670]), array([135]))
0.0
Time to process polygon= 0.5774736404418945
(array([350]), array([481]))
3.0978660153088415
Time to process polygon= 0.6047863960266113
(array([683, 683, 684, 684]), array([141, 142, 141, 142]))
0.0
Time to process polygon= 0.5731375217437744
(array([346]), array([480]))
0.8999999761581421
Time to process polygon= 0.6004166603088379
(array([378]), array([295]))
0.0
Time to process polygon= 0.6017782688140869
(array([365, 365, 366]), array([110, 111, 111]))
0.0
Time to process polygon= 0.7660911083221436
(array([351, 351]), array([221, 222]))
0.0
Time to process polygon= 0.6833028793334961
(array([599, 599, 600, 600]), array([142, 1

(array([659]), array([212]))
0.0
Time to process polygon= 0.5271553993225098
(array([309, 309, 310, 310, 311, 311]), array([243, 244, 243, 244, 243, 244]))
0.0
Time to process polygon= 0.6981015205383301
(array([436, 436, 437, 437]), array([93, 94, 93, 94]))
0.0
Time to process polygon= 0.7765054702758789
(array([594, 594, 594, 595, 595]), array([177, 178, 179, 177, 178]))
0.0
Time to process polygon= 0.6126065254211426
(array([569, 569, 570, 570]), array([217, 218, 217, 218]))
0.0
Time to process polygon= 0.5873720645904541
(array([337]), array([360]))
0.0
Time to process polygon= 0.5829215049743652
(array([351, 351, 352, 352, 352, 353]), array([240, 241, 239, 240, 241, 240]))
0.0
Time to process polygon= 0.6936259269714355
(array([278]), array([232]))
0.0
Time to process polygon= 0.7269887924194336
(array([347, 347, 348, 348]), array([239, 240, 239, 240]))
0.0
Time to process polygon= 0.6819744110107422
(array([617]), array([234]))
0.0
Time to process polygon= 0.5271730422973633
(arr

(array([575, 576]), array([155, 155]))
3.814395388974325
Time to process polygon= 0.6192541122436523
2019-08-23
2019 08 23
/data2/lthapa/2019/STAGEIV/ST4.2019082312.24h.nc
(array([589]), array([231]))
0.0
Time to process polygon= 0.5465235710144043
(array([644, 644]), array([258, 259]))
1.8043632067040185
Time to process polygon= 0.5113236904144287
(array([431]), array([271]))
0.0
Time to process polygon= 0.6011161804199219
(array([670]), array([135]))
0.0
Time to process polygon= 0.5871908664703369
(array([683, 684]), array([141, 141]))
0.0
Time to process polygon= 0.5732369422912598
(array([378, 378, 379]), array([295, 296, 296]))
0.0
Time to process polygon= 0.6157169342041016
(array([365, 366]), array([111, 111]))
0.0
Time to process polygon= 0.7652039527893066
(array([351, 351]), array([221, 222]))
0.0
Time to process polygon= 0.6831908226013184
(array([599, 599, 600, 600]), array([142, 143, 142, 143]))
0.0
Time to process polygon= 0.6222052574157715


In [11]:
#fire_features[fire_features['Current Day']=='2020-07-27']
therest = fire_features[['Incident Number', 'Fire Name', 'Current Day','Lat Fire', 'Lon Fire','Number of VIIRS points', 'A_PCP_GDS5_SFC_acc24h_0', 'APCP_P8_L1_GST0_acc_0','A_PCP_GDS5_SFC_acc24h_1', 'APCP_P8_L1_GST0_acc_1' ]]
therest

#therest.to_csv('fire_features_precip_2019.csv', index=False)
#therest.to_csv('fire_features_precip_2020.csv', index=False)
therest.to_csv('fire_features_precip_1dayout.csv', index=False)

## Helper Functions

In [7]:
#this function calculates the area of each grid in a given grid cell
# LAT and LON should be 2d
def calculate_grid_cell_corners(LAT, LON):
    #we will assume the very edges of the polygons don't touch the boundary of the domain
    lat_corners = (LAT[0:(lat.shape[0]-1),  0:(lat.shape[1])-1] + LAT[1:(lat.shape[0]), 1:(lat.shape[1])])/2
    lon_corners = (LON[0:(lat.shape[0]-1),  0:(lat.shape[1])-1] + LON[1:(lat.shape[0]), 1:(lat.shape[1])])/2
    return lat_corners, lon_corners
    """for ii in range(1,LAT.shape[0]-1):
        for jj in range(1, LAT.shape[1]-1):
            cell_lat = LAT[ii, jj]
            cell_lon = LON[ii, jj]
            SW_lat[ii,jj] = LAT[ii,jj] + (LAT[ii-1,jj-1] - LAT[ii,jj])/2
            SW_lon[ii,jj] = LON[ii,jj] + (LON[ii-1,jj-1] - LON[ii,jj])/2
            SE_lat[ii,jj] = LAT[ii,jj] + (LAT[ii-1,jj-1] - LAT[ii,jj])/2
            SE_lon[ii,jj] = LON[ii,jj] + (LON[ii,jj] - LON[ii-1,jj-1])/2
            NW_lat[ii,jj] = LAT[ii,jj] + (LAT[ii,jj] - LAT[ii-1,jj-1])/2
            NW_lon[ii,jj] = LON[ii,jj] + (LON[ii-1,jj-1] - LON[ii,jj])/2
            NE_lat[ii,jj] = LAT[ii,jj] + (LAT[ii,jj] - LAT[ii-1,jj-1])/2
            NE_lon[ii,jj] = LON[ii,jj] + (LON[ii,jj] - LON[ii-1,jj-1])/2
    return  SW_lat, SW_lon, SE_lat, SE_lon, NW_lat, NW_lon, NE_lat, NE_lon"""

In [8]:
# this function calculates the overlap between the given shape (fire_shape) and given grid (LAT, LON). 
#LAT and LON should be 2D

def calculate_overlaps(lat, lon, lat_corners, lon_corners, lat_start, lat_stop, lon_start, lon_stop, fire_shape):
    overlaps = np.zeros(lat.shape)
    # buffer the fire shape so it has a non zero area
    if fire_shape.area ==0:
        fire_shape = fire_shape.buffer(0.01)
    # find the intersection between the first day's polygon and the  grid
    for ii in range(lat_start, lat_stop):
        for jj in range(lon_start, lon_stop):
            #print('ctr', lat[ii,jj], lon[ii,jj])
            """ SW_lat = lat_corners[ii-1, jj-1]
            SW_lon = lon_corners[ii-1, jj-1]
            SE_lat = lat_corners[ii-1, jj-1]
            SE_lon = lon_corners[ii-1, jj]
            NW_lat = lat_corners[ii, jj-1]
            NW_lon = lon_corners[ii, jj-1]
            NE_lat = lat_corners[ii, jj]
            NE_lon = lon_corners[ii, jj]"""
            #print((lon_corners[ii, jj-1],lat_corners[ii, jj-1]), (lon_corners[ii, jj],lat_corners[ii, jj]), (lon_corners[ii-1, jj],lat_corners[ii-1, jj-1]), (lon_corners[ii-1, jj-1], lat_corners[ii-1, jj-1]))
            poly_cell = Polygon([(lon_corners[ii, jj-1],lat_corners[ii, jj-1]), (lon_corners[ii, jj],lat_corners[ii, jj]), (lon_corners[ii-1, jj],lat_corners[ii-1, jj-1]), (lon_corners[ii-1, jj-1], lat_corners[ii-1, jj-1])])
            overlap_cell = fire_shape.intersection(poly_cell)
            #overlaps are the fraction of the POLYGON in each grid cell
            overlaps[ii,jj] = overlap_cell.area/fire_shape.area
    
    return overlaps

In [ ]:
#geoseries way
        #load in the relevant geometry array
        geojson_path = path.replace('.'+yr+mo+dy+'.nc4', '_grid_polygons.geojson')
        geojson_path = geojson_path.replace('/data2/lthapa/'+yr+'/MERRA2/', './')
        geojson_path = geojson_path.replace('/data2/lthapa/'+yr+'/QFED/', './')
        print(geojson_path)
        grid_polys = gpd.read_file(geojson_path)
        
inds = np.where(grid_polys['geometry'].intersection(poly).area)[0]
            areas = grid_polys['geometry'].intersection(poly).area
            #print(areas[inds])
            #print(areas[inds]/poly.area)
            toc=time.time()
            print('Time elapsed for calculating overlaps for polygon:', toc-tic)


In [9]:
#fnction is from here: https://gis.stackexchange.com/questions/71630/subsetting-a-curvilinear-netcdf-file-roms-model-output-using-a-lon-lat-boundin
def bbox2ij(lon,lat,bbox):
    bbox=np.array(bbox)
    mypath=np.array([bbox[[0,1,1,0]],bbox[[2,2,3,3]]]).T
    p = path.Path(mypath)
    points = np.vstack((lon.flatten(),lat.flatten())).T
    n,m = np.shape(lon)
    inside = p.contains_points(points).reshape((n,m))
    ii,jj = np.meshgrid(range(m),range(n)) #ii is the columns, jj is the rows
    return min(ii[inside]),max(ii[inside]),min(jj[inside]),max(jj[inside])