This code will generate the feature vector, using sub grids to calculate the overlap

This code will calculate today's met and ndays out's met in today's polygon

In [1]:
import pandas as pd
#pd.set_option('display.max_rows', None)
import geopandas as gpd
import matplotlib.pyplot as plt
import os
import cartopy.crs as ccrs
import cartopy
import numpy as np
import netCDF4 as nc
np.set_printoptions(threshold=100000)
from shapely.geometry import Polygon, Point, MultiPoint
from shapely.ops import cascaded_union
from datetime import datetime, timedelta
import time
import warnings
warnings.filterwarnings('ignore')
from joblib import Parallel, delayed

##  Step 0. Throw out fires that have 0 viirs detects on any day. (fires are already filtered to be in the right lat/lon range

In [2]:
# load in the polygons and attributes
fire_polygons = gpd.read_file('fire_polygons_only.geojson')
fire_attributes = pd.read_csv('fire_polygons_attributes.csv')
incidents = pd.read_csv('unique_fires.csv')
print(len(fire_polygons), len(fire_attributes), len(incidents))

#throw out fires that have 0 days with detects
daily_drop_inds = []
incident_drop_inds = []
for item in incidents['Incident Number']:
    pts = fire_attributes['Number of VIIRS points'].values[fire_attributes['Incident Number']==item]
    if len(pts[pts==0])==len(pts):
        #print(item, 'oops all zeros')
        daily_drop_inds = np.append(daily_drop_inds, np.where(fire_attributes['Incident Number']==item)[0])
        incident_drop_inds = np.append(incident_drop_inds, np.where(incidents['Incident Number']==item)[0])

daily_drop_inds = [int(p) for p in daily_drop_inds]
#print(daily_drop_inds)

fire_attributes = fire_attributes.drop(labels= daily_drop_inds)
fire_attributes = fire_attributes.drop(labels='Unnamed: 0', axis=1)
fire_polygons = fire_polygons.drop(labels = daily_drop_inds)
incidents = incidents.drop(labels = incident_drop_inds)
print(len(fire_polygons), len(fire_attributes), len(incidents))

fire_attributes

22280 22280 1354
19137 19137 1036


Incident Number      Fire Name Current Day   Lat Fire    Lon Fire  \
5           10662684.0  PAINTED WAGON  2019-04-08  33.786944 -112.753333   
6           10662684.0  PAINTED WAGON  2019-04-09  33.786944 -112.753333   
7           10662684.0  PAINTED WAGON  2019-04-10  33.786944 -112.753333   
8           10663171.0  LONE MOUNTAIN  2019-05-26  33.808056 -105.738611   
9           10663171.0  LONE MOUNTAIN  2019-05-27  33.808056 -105.738611   
...                ...            ...         ...        ...         ...   
22275       11980587.0        CREEK 5  2020-12-25  33.402646 -117.266795   
22276       11980587.0        CREEK 5  2020-12-26  33.402646 -117.266795   
22277       11980587.0        CREEK 5  2020-12-27  33.402646 -117.266795   
22278       11980587.0        CREEK 5  2020-12-28  33.402646 -117.266795   
22279       11980949.0        CREEK 5  2020-12-24  33.407667 -117.269667   

       Number of VIIRS points  
5                         3.0  
6                         0.0  
7                         0.0  
8                         0.0  
9                         0.0  
...                       ...  
22275                    16.0  
22276                     0.0  
22277                     0.0  
22278                     0.0  
22279                     2.0  

[19137 rows x 6 columns]

## 1. Figure out the start and end date we will use for each fire

In [ ]:
# first check what fraction of the fire lifetimes are 0 days
for item in incidents['Incident Number']:
    pts = fire_attributes['Number of VIIRS points'].values[fire_attributes['Incident Number']==item]
    #print(len(np.where(pts==0)[0]))
    print('The fire lifetime is ', len(np.where(pts!=0)[0])*100/len(pts), '% nonzero detections')

In [3]:
keep_days = []
for item in incidents['Incident Number']:
    pts = fire_attributes['Number of VIIRS points'].values[fire_attributes['Incident Number']==item]
    dys = fire_attributes['Current Day'].values[fire_attributes['Incident Number']==item]
    nonzero = np.where(pts!=0)[0]
    first_day = dys[nonzero[0]]
    last_day = dys[nonzero[len(nonzero)-1]]
    keep_days = np.append(keep_days, np.where((fire_attributes['Incident Number']==item)&(fire_attributes['Current Day']>=first_day)&(fire_attributes['Current Day']<=last_day))[0])

keep_days = [int(p) for p in keep_days]
print(len(keep_days))
fire_attributes = fire_attributes.iloc[keep_days, :]
fire_polygons = fire_polygons.iloc[keep_days, :]
fire_attributes = fire_attributes.reset_index(drop=True) #reset the indices beecause we dropped some
fire_polygons = fire_polygons.reset_index(drop=True) #reset the indices beecause we dropped some

fire_polygons

8161


geometry
0     POLYGON ((-112.75455 33.78632, -112.76012 33.7...
1     POLYGON ((-105.73275 33.80235, -105.73861 33.8...
2     POLYGON ((-105.73275 33.80235, -105.73861 33.8...
3     POLYGON ((-105.73275 33.80235, -105.73861 33.8...
4     POLYGON ((-105.73275 33.80235, -105.73861 33.8...
...                                                 ...
8156  POLYGON ((-112.11669 34.11898, -112.12564 34.1...
8157  POLYGON ((-117.03702 33.90632, -117.04484 33.9...
8158  POLYGON ((-117.27595 33.37881, -117.27495 33.3...
8159  POLYGON ((-117.29549 33.36558, -117.29713 33.4...
8160  POLYGON ((-117.27595 33.37881, -117.26967 33.4...

[8161 rows x 1 columns]

## 2. Loop through the days and get the raw features (temp at different pressure levels, wind, pressure, precip, terrain info) and the labels (QFED PM2.5 from the next day)

In [20]:
ndays = 2
# dictionaries that track the variables, dimensions, times and levels
varis = {'/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.*.nc4':['TLML', 'QLML', 'SPEEDLML', 'PS'], 
        '/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.*.nc4': ['T', 'QV'],
         '/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.*.nc4': ['PBLH', 'TCZPBL']} #don't have september for this!

#0=lat, 1=lon, 2=time, 3=level 
dims = {'/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.*.nc4':['lat', 'lon', 'time'], 
       '/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.*.nc4':['lat', 'lon', 'time', 'lev'],
        '/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.*.nc4':['lat', 'lon', 'time']}

times = {'TLML':12, 'QLML':12, 'SPEEDLML':12, 'PS':12, 'T':12, 'QV':12, 'PBLH':12, 'TCZPBL':12}
levels = {'T':[500, 700], 'QV':[700]} 
file_suffix = '.nc4'

#pre-allocate the data frame
num_days = len(fire_attributes)
fire_features = gpd.GeoDataFrame({'Incident Number': np.nan*np.zeros(num_days), 'Fire Name': np.nan*np.zeros(num_days), 
                             'Current Day': np.nan*np.zeros(num_days), 'Lat Fire': np.nan*np.zeros(num_days), 
                             'Lon Fire': np.nan*np.zeros(num_days), 'Number of VIIRS points': np.nan*np.zeros(num_days),
                            'TLML_12Z_0': np.nan*np.zeros(num_days), 'QLML_12Z_0': np.nan*np.zeros(num_days),
                            'SPEEDLML_12Z_0': np.nan*np.zeros(num_days),'PS_12Z_0': np.nan*np.zeros(num_days),
                            'T_12Z_700mb_0': np.nan*np.zeros(num_days),'T_12Z_500mb_0': np.nan*np.zeros(num_days),
                            'QV_12Z_700mb_0': np.nan*np.zeros(num_days),'PBLH_12Z_0': np.nan*np.zeros(num_days), 
                            'TCZPBL_12Z_0': np.nan*np.zeros(num_days),'TLML_12Z_1': np.nan*np.zeros(num_days), 
                            'QLML_12Z_1': np.nan*np.zeros(num_days), 'SPEEDLML_12Z_1': np.nan*np.zeros(num_days),
                                  'PS_12Z_1': np.nan*np.zeros(num_days),'T_12Z_700mb_1': np.nan*np.zeros(num_days),
                                  'T_12Z_500mb_1': np.nan*np.zeros(num_days),'QV_12Z_700mb_1': np.nan*np.zeros(num_days),
                                  'PBLH_12Z_1': np.nan*np.zeros(num_days), 'TCZPBL_12Z_1': np.nan*np.zeros(num_days),  
                                  'geometry': np.nan*np.zeros(num_days)}) # pre-allocate the dataframe

#'fccs': np.nan*np.zeros(num_days),'slp': np.nan*np.zeros(num_days),'asp': np.nan*np.zeros(num_days), 
fire_features['Incident Number'] = fire_attributes['Incident Number'].values
fire_features['Fire Name'] = fire_attributes['Fire Name'].values
fire_features['Current Day'] = fire_attributes['Current Day'].values
fire_features['Lat Fire'] = fire_attributes['Lat Fire'].values
fire_features['Lon Fire'] = fire_attributes['Lon Fire'].values
fire_features['Number of VIIRS points'] = fire_attributes['Number of VIIRS points'].values
fire_features['geometry'] = fire_polygons['geometry'].values

#print(fire_features)
unique_days = np.unique(fire_features['Current Day'].values)
print(len(unique_days))
for dd in range(len(unique_days)):
    #print(unique_days[dd])
    for dyf in range(ndays):
        date=np.datetime64(unique_days[dd])+np.array(dyf, 'timedelta64[D]')
        print(date)
        date=str(date)
        yr = date[0:4]
        mo = date[5:7]
        dy = date[8:10]
        #print(yr, mo,dy)
        #find the polygons for the given day

        for i in varis : #loop over the file names
            #get the path to the file
            path = '/data2/lthapa/'+yr+i
            if '*' in path:
                path = path.replace('*', yr+mo+dy)
            if np.datetime64(date)>=np.datetime64('2020-09-01') and np.datetime64(date)<=np.datetime64('2020-09-30'):
                path = path.replace('400', '401')

            #load the file in as a netcdf dataset
            print(path)
            dat = nc.Dataset(path)
            ndims = len(dims[i])
            if ndims ==2: #lat and lon
                lat = dat[dims[i][0]][:]
                lon = dat[dims[i][1]][:]
            elif ndims == 3: #lat, lon, and time
                lat = dat[dims[i][0]][:]
                lon = dat[dims[i][1]][:]
                t = dat[dims[i][2]][:]
            elif ndims ==4: #lat,lon,time,and level
                lat = dat[dims[i][0]][:]
                lon = dat[dims[i][1]][:]
                t = dat[dims[i][2]][:]
                lev = dat[dims[i][3]][:]
            if len(lat.shape)==1:
                lon, lat = np.meshgrid(lon, lat)

            #calculate the areas of the lat/lon grid for the DATASET
            lat_corners, lon_corners = calculate_grid_cell_corners(lat, lon)
            inds = np.where(fire_features['Current Day']==unique_days[dd])[0]
            polys = fire_features['geometry'].iloc[inds].values
            print(inds)
            for p in range(len(inds)):
                #tic = time.time()
                #add a halo to the polygon
                poly = polys[p]
                poly_buff = poly.buffer(2) #buffer doesn't matter!
                # get the bounds of the buffered polygon
                w,s,e,n = poly_buff.bounds
                #print(w,s,e,n)
                s_ind = np.unique(np.argmin(np.abs(lat-s), axis=0))[0]
                n_ind = np.unique(np.argmin(np.abs(lat-n), axis=0))[0]
                w_ind = np.unique(np.argmin(np.abs(lon-w), axis=1))[0]
                e_ind = np.unique(np.argmin(np.abs(lon-e), axis=1))[0]


                #tic = time.time()
                overlaps = calculate_overlaps(lat,lon,lat_corners,lon_corners,s_ind,n_ind,w_ind,e_ind, poly) #calculate the overlap between the poly and the lat/lon grid
                #print(np.where(overlaps!=0))
                #toc = time.time()
                #print('Time elapsed for calculating overlaps for polygon:', toc-tic)
                for j in varis[i]: #loop over the variable names, which are lists
                    var = dat[j][:]
                    #print('the dimensions of', j, 'are', var.shape, 'and', j, 'has', ndims, 'dimensions')
                    #select the times and levels we need
                    if ndims ==2: #lat and lon
                        # calculate overlap
                        #print(var.shape)
                        var_weighted = np.multiply(var,overlaps)
                        var_ave = np.nansum(var_weighted)
                        name_in_table = j
                        fire_features.loc[inds[p],name_in_table] = var_ave

                    elif ndims == 3: #lat, lon, and time
                        #select the needed times (12Z)
                        if j in times.keys():
                            ind_time = np.argmin(np.abs(times[j]*60-t))
                            #filter the variable by time
                            var = var[ind_time, :, :]
                            #print(var.shape)
                            var_weighted = np.multiply(var,overlaps)
                            var_ave = np.nansum(var_weighted)
                            name_in_table = j+'_'+str(times[j])+'Z_'+str(dyf)
                            fire_features.loc[inds[p],name_in_table] = var_ave

                    elif ndims ==4: #lat,lon,time,and level
                        #select the needed times and levels
                        if j in times.keys():
                            ind_time = np.argmin(np.abs(times[j]*60-t))
                            #filter the variable by time
                            var = var[ind_time, :, :, :]
                            #filter by levels
                            if j in levels.keys(): #if there are levels, loop through them
                                for l in levels[j]:
                                    ind_lev = np.argmin(np.abs(l-lev))
                                    var_weighted = np.multiply(var[ind_lev, :, :], overlaps)
                                    var_ave = np.nansum(var_weighted)
                                    name_in_table = j+'_'+str(times[j])+'Z_'+str(l)+'mb_'+str(dyf)
                                    fire_features.loc[inds[p],name_in_table] = var_ave
                #toc = time.time()
                #print('Time to process polygon=',toc-tic)
            dat.close() 
fire_features

442
2019-02-17
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190217.nc4
[470]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190217.nc4
[470]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190217.nc4
[470]
2019-02-18
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190218.nc4
[470]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190218.nc4
[470]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190218.nc4
[470]
2019-02-18
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190218.nc4
[471]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190218.nc4
[471]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190218.nc4
[471]
2019-02-19
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190219.nc4
[471]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190219.nc4
[471]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190219.nc4
[471]
2019

[ 217 1174 1495]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190505.nc4
[ 217 1174 1495]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190505.nc4
[ 217 1174 1495]
2019-05-06
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190506.nc4
[ 217 1174 1495]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190506.nc4
[ 217 1174 1495]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190506.nc4
[ 217 1174 1495]
2019-05-06
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190506.nc4
[ 215  218 1103 1175 1496]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190506.nc4
[ 215  218 1103 1175 1496]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190506.nc4
[ 215  218 1103 1175 1496]
2019-05-07
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190507.nc4
[ 215  218 1103 1175 1496]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190507.nc4
[ 215  218 1103 1175 1496]


/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190527.nc4
[38]
2019-05-28
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190528.nc4
[38]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190528.nc4
[38]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190528.nc4
[38]
2019-05-28
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190528.nc4
[39]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190528.nc4
[39]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190528.nc4
[39]
2019-05-29
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190529.nc4
[39]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190529.nc4
[39]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190529.nc4
[39]
2019-05-29
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190529.nc4
[  40 1426]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190529.nc4
[  40 1426]
/data2

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190610.nc4
[   2   54   79  487 1399 1438 1445 1546]
2019-06-11
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190611.nc4
[   2   54   79  487 1399 1438 1445 1546]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190611.nc4
[   2   54   79  487 1399 1438 1445 1546]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190611.nc4
[   2   54   79  487 1399 1438 1445 1546]
2019-06-11
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190611.nc4
[   3   55   80  488  645  646 1400 1439 1547]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190611.nc4
[   3   55   80  488  645  646 1400 1439 1547]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190611.nc4
[   3   55   80  488  645  646 1400 1439 1547]
2019-06-12
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190612.nc4
[   3   55   80  488  645  646 1400 1439 1547]
/data2/lthapa/2019/MERRA2/W

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190622.nc4
[  14  176  499 1411 1531 2168 2268 2280]
2019-06-23
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190623.nc4
[  14  176  499 1411 1531 2168 2268 2280]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190623.nc4
[  14  176  499 1411 1531 2168 2268 2280]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190623.nc4
[  14  176  499 1411 1531 2168 2268 2280]
2019-06-23
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190623.nc4
[  15  177  500 1177 1412 1532 2269 2281]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190623.nc4
[  15  177  500 1177 1412 1532 2269 2281]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190623.nc4
[  15  177  500 1177 1412 1532 2269 2281]
2019-06-24
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190624.nc4
[  15  177  500 1177 1412 1532 2269 2281]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.ins

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190704.nc4
[ 166  179  182  510  676 1187 1911 1970 2405 2433 2444 2469 2488 2491
 2495]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190704.nc4
[ 166  179  182  510  676 1187 1911 1970 2405 2433 2444 2469 2488 2491
 2495]
2019-07-04
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190704.nc4
[  60  167  180  183  511  677 1756 1757 1912 1971 2118 2406 2434 2445
 2470 2489]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190704.nc4
[  60  167  180  183  511  677 1756 1757 1912 1971 2118 2406 2434 2445
 2470 2489]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190704.nc4
[  60  167  180  183  511  677 1756 1757 1912 1971 2118 2406 2434 2445
 2470 2489]
2019-07-05
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190705.nc4
[  60  167  180  183  511  677 1756 1757 1912 1971 2118 2406 2434 2445
 2470 2489]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190714.nc4
[ 116  191  194  686 1341 1659 1980 2255 2415 2454 2479]
2019-07-14
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190714.nc4
[  95  102  117  126  195  733 1342 1981 2243 2256 2416 2455 2480]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190714.nc4
[  95  102  117  126  195  733 1342 1981 2243 2256 2416 2455 2480]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190714.nc4
[  95  102  117  126  195  733 1342 1981 2243 2256 2416 2455 2480]
2019-07-15
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190715.nc4
[  95  102  117  126  195  733 1342 1981 2243 2256 2416 2455 2480]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190715.nc4
[  95  102  117  126  195  733 1342 1981 2243 2256 2416 2455 2480]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190715.nc4
[  95  102  117  126  195  733 1342 1981 2243 2256 2416 2455 2480]
2019-07-

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190722.nc4
[  93  113  124  132  202  404  741 1073 1325 1349 1568 1574 1988 2250]
2019-07-22
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190722.nc4
[  94  125  133  203  742 1074 1350 1575 1989 2251]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190722.nc4
[  94  125  133  203  742 1074 1350 1575 1989 2251]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190722.nc4
[  94  125  133  203  742 1074 1350 1575 1989 2251]
2019-07-23
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190723.nc4
[  94  125  133  203  742 1074 1350 1575 1989 2251]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190723.nc4
[  94  125  133  203  742 1074 1350 1575 1989 2251]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190723.nc4
[  94  125  133  203  742 1074 1350 1575 1989 2251]
2019-07-23
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190723.nc4

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190730.nc4
[ 141  214  361  432  473  585  589  750 1082 1085 1087 1236 1274 1312
 1358 1583 1670 1860 1923 1997 2038 2106 2149 2329 2346 2358 2425]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190730.nc4
[ 141  214  361  432  473  585  589  750 1082 1085 1087 1236 1274 1312
 1358 1583 1670 1860 1923 1997 2038 2106 2149 2329 2346 2358 2425]
2019-07-31
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190731.nc4
[ 141  214  361  432  473  585  589  750 1082 1085 1087 1236 1274 1312
 1358 1583 1670 1860 1923 1997 2038 2106 2149 2329 2346 2358 2425]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190731.nc4
[ 141  214  361  432  473  585  589  750 1082 1085 1087 1236 1274 1312
 1358 1583 1670 1860 1923 1997 2038 2106 2149 2329 2346 2358 2425]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190731.nc4
[ 141  214  361  432  473  585  589  750 1082 1085 1087 1236 1274 1312
 

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190806.nc4
[ 147  231  256  304  317  367  438  479  582  595  756  799  815  839
  858  966  967 1000 1037 1093 1214 1227 1242 1273 1280 1315 1319 1327
 1364 1468 1589 1676 1866 1924 2003 2044 2071 2157 2335 2364]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190806.nc4
[ 147  231  256  304  317  367  438  479  582  595  756  799  815  839
  858  966  967 1000 1037 1093 1214 1227 1242 1273 1280 1315 1319 1327
 1364 1468 1589 1676 1866 1924 2003 2044 2071 2157 2335 2364]
2019-08-06
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190806.nc4
[ 148  232  305  318  368  439  480  596  757  800  816  859  930 1001
 1038 1094 1228 1243 1281 1316 1320 1328 1365 1590 1677 1867 1925 2004
 2045 2072 2158 2336 2365]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190806.nc4
[ 148  232  305  318  368  439  480  596  757  800  816  859  930 1001
 1038 1094 1228 1243 1281 1316 1320 1328 1365 159

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190811.nc4
[ 153  237  310  323  373  444  601  762  805  842  864  887 1099 1200
 1248 1286 1333 1370 1447 1471 1595 1682 1872 1930 2009 2050 2077 2163
 2370 2503 2657 2666]
2019-08-12
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190812.nc4
[ 153  237  310  323  373  444  601  762  805  842  864  887 1099 1200
 1248 1286 1333 1370 1447 1471 1595 1682 1872 1930 2009 2050 2077 2163
 2370 2503 2657 2666]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190812.nc4
[ 153  237  310  323  373  444  601  762  805  842  864  887 1099 1200
 1248 1286 1333 1370 1447 1471 1595 1682 1872 1930 2009 2050 2077 2163
 2370 2503 2657 2666]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190812.nc4
[ 153  237  310  323  373  444  601  762  805  842  864  887 1099 1200
 1248 1286 1333 1370 1447 1471 1595 1682 1872 1930 2009 2050 2077 2163
 2370 2503 2657 2666]
2019-08-12
/data2/lthapa/2019/MERRA2/WEST

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190817.nc4
[ 242  328  378  407  449  546  606  767  810  818  847  869  892  910
  969 1112 1139 1205 1253 1291 1375 1476 1600 1687 1818 1877 1935 2014
 2055 2082 2111 2375 2508 2662 2671]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190817.nc4
[ 242  328  378  407  449  546  606  767  810  818  847  869  892  910
  969 1112 1139 1205 1253 1291 1375 1476 1600 1687 1818 1877 1935 2014
 2055 2082 2111 2375 2508 2662 2671]
2019-08-17
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190817.nc4
[ 243  329  379  405  408  450  607  768  811  819  848  870  893  911
  970 1113 1206 1254 1292 1376 1477 1601 1688 1878 1936 2015 2056 2083
 2376 2509 2672]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190817.nc4
[ 243  329  379  405  408  450  607  768  811  819  848  870  893  911
  970 1113 1206 1254 1292 1376 1477 1601 1688 1878 1936 2015 2056 2083
 2376 2509 2672]
/data2/lthapa/2019/ME

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190822.nc4
[ 248  334  384  455  612  773  824  853  875  916  951  975 1118 1142
 1211 1259 1297 1381 1482 1516 1520 1528 1606 1661 1662 1693 1883 1941
 2020 2061 2088 2171 2230 2381 2677 2696]
2019-08-23
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190823.nc4
[ 248  334  384  455  612  773  824  853  875  916  951  975 1118 1142
 1211 1259 1297 1381 1482 1516 1520 1528 1606 1661 1662 1693 1883 1941
 2020 2061 2088 2171 2230 2381 2677 2696]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190823.nc4
[ 248  334  384  455  612  773  824  853  875  916  951  975 1118 1142
 1211 1259 1297 1381 1482 1516 1520 1528 1606 1661 1662 1693 1883 1941
 2020 2061 2088 2171 2230 2381 2677 2696]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190823.nc4
[ 248  334  384  455  612  773  824  853  875  916  951  975 1118 1142
 1211 1259 1297 1381 1482 1516 1520 1528 1606 1661 1662 1693 1883 1941
 20

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190828.nc4
[ 340  390  461  618  776  830  881  898  900  922  938  957  981 1124
 1148 1218 1265 1303 1387 1448 1488 1526 1537 1699 1826 1889 1947 1966
 2026 2067 2094 2139 2140 2177 2236 2387 2683 2702]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190828.nc4
[ 340  390  461  618  776  830  881  898  900  922  938  957  981 1124
 1148 1218 1265 1303 1387 1448 1488 1526 1537 1699 1826 1889 1947 1966
 2026 2067 2094 2139 2140 2177 2236 2387 2683 2702]
2019-08-29
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190829.nc4
[ 340  390  461  618  776  830  881  898  900  922  938  957  981 1124
 1148 1218 1265 1303 1387 1448 1488 1526 1537 1699 1826 1889 1947 1966
 2026 2067 2094 2139 2140 2177 2236 2387 2683 2702]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190829.nc4
[ 340  390  461  618  776  830  881  898  900  922  938  957  981 1124
 1148 1218 1265 1303 1387 1448 1488 1526 153

2019-09-03
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190903.nc4
[ 345  395  466  623  781  835  905  943  962  986 1003 1129 1223 1270
 1308 1392 1453 1542 1704 1761 1822 1828 1836 1894 1952 2031 2099 2119
 2120 2145 2182 2241 2392 2513 2618 2688 2707]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190903.nc4
[ 345  395  466  623  781  835  905  943  962  986 1003 1129 1223 1270
 1308 1392 1453 1542 1704 1761 1822 1828 1836 1894 1952 2031 2099 2119
 2120 2145 2182 2241 2392 2513 2618 2688 2707]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190903.nc4
[ 345  395  466  623  781  835  905  943  962  986 1003 1129 1223 1270
 1308 1392 1453 1542 1704 1761 1822 1828 1836 1894 1952 2031 2099 2119
 2120 2145 2182 2241 2392 2513 2618 2688 2707]
2019-09-03
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190903.nc4
[ 313  346  396  467  624  782  836  906  944  963  987 1004 1224 1271
 1309 1393 1454 1543 1705 1762 1780 1829 1837 18

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190908.nc4
[ 401  414  539  628  630  632  786  991 1008 1029 1155 1458 1709 1766
 1841 1957 2122 2187 2287 2517 2573 2585 2594 2598 2606 2624 2632 2712]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190908.nc4
[ 401  414  539  628  630  632  786  991 1008 1029 1155 1458 1709 1766
 1841 1957 2122 2187 2287 2517 2573 2585 2594 2598 2606 2624 2632 2712]
2019-09-08
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190908.nc4
[ 402  415  538  540  581  633  787  992 1009 1030 1041 1156 1612 1613
 1616 1710 1767 1783 1958 2123 2188 2288 2518 2574 2586 2595 2599 2607
 2625 2633 2713]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190908.nc4
[ 402  415  538  540  581  633  787  992 1009 1030 1041 1156 1612 1613
 1616 1710 1767 1783 1958 2123 2188 2288 2518 2574 2586 2595 2599 2607
 2625 2633 2713]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190908.nc4
[ 402  415  538  540

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190915.nc4
[ 639  793 1015 1036 1047 1162 1622 1716 1773 1789 2194 2294 2403 2524
 2569 2580 2613 2639 2647 2719]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190915.nc4
[ 639  793 1015 1036 1047 1162 1622 1716 1773 1789 2194 2294 2403 2524
 2569 2580 2613 2639 2647 2719]
2019-09-15
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190915.nc4
[ 547  640  794  855  857  998 1016 1048 1163 1623 1663 1717 1774 1790
 2195 2295 2404 2525 2570 2581 2614 2640 2648 2720]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190915.nc4
[ 547  640  794  855  857  998 1016 1048 1163 1623 1663 1717 1774 1790
 2195 2295 2404 2525 2570 2581 2614 2640 2648 2720]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190915.nc4
[ 547  640  794  855  857  998 1016 1048 1163 1623 1663 1717 1774 1790
 2195 2295 2404 2525 2570 2581 2614 2640 2648 2720]
2019-09-16
/data2/lthapa/2019/MERRA2/WESTUS_MERRA

[ 555 1024 1056 1171 1631 1725 1798 1852 2203 2303 2533 2728]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190923.nc4
[ 555 1024 1056 1171 1631 1725 1798 1852 2203 2303 2533 2728]
2019-09-24
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190924.nc4
[ 555 1024 1056 1171 1631 1725 1798 1852 2203 2303 2533 2728]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190924.nc4
[ 555 1024 1056 1171 1631 1725 1798 1852 2203 2303 2533 2728]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190924.nc4
[ 555 1024 1056 1171 1631 1725 1798 1852 2203 2303 2533 2728]
2019-09-24
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20190924.nc4
[ 556 1057 1632 1726 1799 2204 2304 2534 2729]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20190924.nc4
[ 556 1057 1632 1726 1799 2204 2304 2534 2729]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190924.nc4
[ 556 1057 1632 1726 1799 2204 2304 2534 2729]
2019-09-25
/data

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191004.nc4
[ 267  566 1067 1642 1736 1809 2214 2314 2544]
2019-10-05
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191005.nc4
[ 267  566 1067 1642 1736 1809 2214 2314 2544]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191005.nc4
[ 267  566 1067 1642 1736 1809 2214 2314 2544]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191005.nc4
[ 267  566 1067 1642 1736 1809 2214 2314 2544]
2019-10-05
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191005.nc4
[ 268  567 1643 1737 1810 2215 2315 2545]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191005.nc4
[ 268  567 1643 1737 1810 2215 2315 2545]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191005.nc4
[ 268  567 1643 1737 1810 2215 2315 2545]
2019-10-06
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191006.nc4
[ 268  567 1643 1737 1810 2215 2315 2545]
/data2/lthapa/2019/MERRA2/W

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191015.nc4
[ 278  525  697 1503 1653 1747 2225 2555]
2019-10-16
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191016.nc4
[ 278  525  697 1503 1653 1747 2225 2555]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191016.nc4
[ 278  525  697 1503 1653 1747 2225 2555]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191016.nc4
[ 278  525  697 1503 1653 1747 2225 2555]
2019-10-16
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191016.nc4
[ 279  526  698 1504 1654 1748 1842 2226 2556]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191016.nc4
[ 279  526  698 1504 1654 1748 1842 2226 2556]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191016.nc4
[ 279  526  698 1504 1654 1748 1842 2226 2556]
2019-10-17
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191017.nc4
[ 279  526  698 1504 1654 1748 1842 2226 2556]
/data2/lthapa/2019/MERRA2/W

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191027.nc4
[ 290  302  354  537  709  838 2567]
2019-10-28
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191028.nc4
[ 290  302  354  537  709  838 2567]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191028.nc4
[ 290  302  354  537  709  838 2567]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191028.nc4
[ 290  302  354  537  709  838 2567]
2019-10-28
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191028.nc4
[291 303 349 355 710]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191028.nc4
[291 303 349 355 710]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191028.nc4
[291 303 349 355 710]
2019-10-29
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191029.nc4
[291 303 349 355 710]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191029.nc4
[291 303 349 355 710]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d

/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191111.nc4
[724]
2019-11-12
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191112.nc4
[724]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191112.nc4
[724]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191112.nc4
[724]
2019-11-12
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191112.nc4
[ 725 1188]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191112.nc4
[ 725 1188]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191112.nc4
[ 725 1188]
2019-11-13
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191113.nc4
[ 725 1188]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20191113.nc4
[ 725 1188]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20191113.nc4
[ 725 1188]
2019-11-13
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20191113.nc4
[ 726 1189]
/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.i

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200406.nc4
[2739]
2020-04-07
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200407.nc4
[2739]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200407.nc4
[2739]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200407.nc4
[2739]
2020-04-11
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200411.nc4
[2737]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200411.nc4
[2737]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200411.nc4
[2737]
2020-04-12
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200412.nc4
[2737]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200412.nc4
[2737]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200412.nc4
[2737]
2020-04-12
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200412.nc4
[2738]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200412.nc4
[27

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200519.nc4
[2749 2775 2776]
2020-05-20
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200520.nc4
[2751 2780 2793]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200520.nc4
[2751 2780 2793]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200520.nc4
[2751 2780 2793]
2020-05-21
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200521.nc4
[2751 2780 2793]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200521.nc4
[2751 2780 2793]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200521.nc4
[2751 2780 2793]
2020-05-21
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200521.nc4
[2752 2781]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200521.nc4
[2752 2781]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200521.nc4
[2752 2781]
2020-05-22
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200522.nc

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200603.nc4
[2949]
2020-06-04
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200604.nc4
[2949]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200604.nc4
[2949]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200604.nc4
[2949]
2020-06-04
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200604.nc4
[2836]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200604.nc4
[2836]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200604.nc4
[2836]
2020-06-05
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200605.nc4
[2836]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200605.nc4
[2836]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200605.nc4
[2836]
2020-06-05
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200605.nc4
[2820 2911 2915]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.202006

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200614.nc4
[2919 2925 2941 2957 2982 2987 2988 2997 3042 3067 3072 3085 3118 3159
 3164]
2020-06-15
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200615.nc4
[2919 2925 2941 2957 2982 2987 2988 2997 3042 3067 3072 3085 3118 3159
 3164]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200615.nc4
[2919 2925 2941 2957 2982 2987 2988 2997 3042 3067 3072 3085 3118 3159
 3164]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200615.nc4
[2919 2925 2941 2957 2982 2987 2988 2997 3042 3067 3072 3085 3118 3159
 3164]
2020-06-15
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200615.nc4
[2843 2895 2920 2926 2958 2983 2998 3043 3068 3086 3119 3160 3165]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200615.nc4
[2843 2895 2920 2926 2958 2983 2998 3043 3068 3086 3119 3160 3165]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200615.nc4
[2843 2895 2920 2926 

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200624.nc4
[2852 2871 2903 2935 2951 2967 2973 3007 3052 3095 3128]
2020-06-25
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200625.nc4
[2852 2871 2903 2935 2951 2967 2973 3007 3052 3095 3128]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200625.nc4
[2852 2871 2903 2935 2951 2967 2973 3007 3052 3095 3128]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200625.nc4
[2852 2871 2903 2935 2951 2967 2973 3007 3052 3095 3128]
2020-06-25
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200625.nc4
[2853 2872 2936 2968 2974 2975 3008 3053 3096 3129]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200625.nc4
[2853 2872 2936 2968 2974 2975 3008 3053 3096 3129]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200625.nc4
[2853 2872 2936 2968 2974 2975 3008 3053 3096 3129]
2020-06-26
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200626.nc4

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200705.nc4
[2808 2881 3017 3105 3153 3444 3446 3458 3461 3516 3541 3566]
2020-07-05
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200705.nc4
[2809 2882 3018 3106 3154 3357 3410 3447 3517 3542 3567]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200705.nc4
[2809 2882 3018 3106 3154 3357 3410 3447 3517 3542 3567]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200705.nc4
[2809 2882 3018 3106 3154 3357 3410 3447 3517 3542 3567]
2020-07-06
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200706.nc4
[2809 2882 3018 3106 3154 3357 3410 3447 3517 3542 3567]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200706.nc4
[2809 2882 3018 3106 3154 3357 3410 3447 3517 3542 3567]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200706.nc4
[2809 2882 3018 3106 3154 3357 3410 3447 3517 3542 3567]
2020-07-06
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200715.nc4
[2891 3027 3551 3922 3924 4153 4178 4323 4342 4366 4372 4378 4384 4386
 4420 4421]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200715.nc4
[2891 3027 3551 3922 3924 4153 4178 4323 4342 4366 4372 4378 4384 4386
 4420 4421]
2020-07-15
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200715.nc4
[2892 3028 3195 3436 3442 3454 3456 3552 3923 3925 4154 4179 4324 4367
 4373 4379 4387 4422]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200715.nc4
[2892 3028 3195 3436 3442 3454 3456 3552 3923 3925 4154 4179 4324 4367
 4373 4379 4387 4422]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200715.nc4
[2892 3028 3195 3436 3442 3454 3456 3552 3923 3925 4154 4179 4324 4367
 4373 4379 4387 4422]
2020-07-16
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200716.nc4
[2892 3028 3195 3436 3442 3454 3456 3552 3923 3925 4154 4179 4324 4367
 4373 4379 4387 4422]
/d

[3452 3487 3490 3505 3531 3712 3727 3732 3756 3913 3921 4313 4332]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200724.nc4
[3452 3487 3490 3505 3531 3712 3727 3732 3756 3913 3921 4313 4332]
2020-07-24
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200724.nc4
[3453 3470 3506 3532 3574 3713 3728 3733 3757 3914 4314 4333]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200724.nc4
[3453 3470 3506 3532 3574 3713 3728 3733 3757 3914 4314 4333]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200724.nc4
[3453 3470 3506 3532 3574 3713 3728 3733 3757 3914 4314 4333]
2020-07-25
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200725.nc4
[3453 3470 3506 3532 3574 3713 3728 3733 3757 3914 4314 4333]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200725.nc4
[3453 3470 3506 3532 3574 3713 3728 3733 3757 3914 4314 4333]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200725.nc4
[3453 3470 3506 3532 35

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200802.nc4
[3170 3204 3309 3363 3371 3409 3500 3581 3692 3741 3749 3772 3953 4156
 4158 4164 4167 4170 4184 4297 4300 4302 4317 4320 4407]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200802.nc4
[3170 3204 3309 3363 3371 3409 3500 3581 3692 3741 3749 3772 3953 4156
 4158 4164 4167 4170 4184 4297 4300 4302 4317 4320 4407]
2020-08-03
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200803.nc4
[3170 3204 3309 3363 3371 3409 3500 3581 3692 3741 3749 3772 3953 4156
 4158 4164 4167 4170 4184 4297 4300 4302 4317 4320 4407]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200803.nc4
[3170 3204 3309 3363 3371 3409 3500 3581 3692 3741 3749 3772 3953 4156
 4158 4164 4167 4170 4184 4297 4300 4302 4317 4320 4407]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200803.nc4
[3170 3204 3309 3363 3371 3409 3500 3581 3692 3741 3749 3772 3953 4156
 4158 4164 4167 4170 4184 4297 4300 4302 

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200810.nc4
[3177 3211 3316 3378 3588 3682 3685 3700 3722 3752 3779 3886 3910 3918
 3960 4172 4174 4191 4301 4418]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200810.nc4
[3177 3211 3316 3378 3588 3682 3685 3700 3722 3752 3779 3886 3910 3918
 3960 4172 4174 4191 4301 4418]
2020-08-10
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200810.nc4
[3178 3212 3317 3379 3589 3686 3701 3723 3753 3780 3887 3911 3919 3961
 4173 4175 4192 4346 4364]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200810.nc4
[3178 3212 3317 3379 3589 3686 3701 3723 3753 3780 3887 3911 3919 3961
 4173 4175 4192 4346 4364]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200810.nc4
[3178 3212 3317 3379 3589 3686 3701 3723 3753 3780 3887 3911 3919 3961
 4173 4175 4192 4346 4364]
2020-08-11
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200811.nc4
[3178 3212 3317 3379 3589 3686 3701 3723

2020-08-17
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200817.nc4
[3185 3219 3324 3386 3596 3787 3894 3934 3968 3995 4032 4070 4353 4778
 4903 5165 5177 5178 5237 5238 5239 5263 5302 5414 5447 5501 5639 5641
 5643 5864 5866 5887 5895 5981 6040 6052 6053 6085 6100 6103 6107 6109
 6146 6158 6244 6265 6327 6329 6349 6356 6420 6439 6441 6524 6526 6533
 6536 6596 6598 6601 6607 6677]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200817.nc4
[3185 3219 3324 3386 3596 3787 3894 3934 3968 3995 4032 4070 4353 4778
 4903 5165 5177 5178 5237 5238 5239 5263 5302 5414 5447 5501 5639 5641
 5643 5864 5866 5887 5895 5981 6040 6052 6053 6085 6100 6103 6107 6109
 6146 6158 6244 6265 6327 6329 6349 6356 6420 6439 6441 6524 6526 6533
 6536 6596 6598 6601 6607 6677]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200817.nc4
[3185 3219 3324 3386 3596 3787 3894 3934 3968 3995 4032 4070 4353 4778
 4903 5165 5177 5178 5237 5238 5239 5263 5302 5414 5447 5501 5639 5

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200820.nc4
[3222 3327 3389 3599 3790 3897 3937 3971 3998 4035 4073 4356 5159 5163
 5168 5181 5189 5232 5266 5278 5296 5301 5306 5307 5450 5504 5593 5595
 5646 5712 5755 5833 5836 5869 5890 5898 5984 5986 6032 6036 6038 6043
 6056 6076 6083 6088 6112 6149 6161 6247 6268 6332 6345 6352 6354 6359
 6412 6415 6423 6444 6495 6516 6519 6529 6539 6571 6604 6610 6637 6662
 6665]
2020-08-21
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200821.nc4
[3222 3327 3389 3599 3790 3897 3937 3971 3998 4035 4073 4356 5159 5163
 5168 5181 5189 5232 5266 5278 5296 5301 5306 5307 5450 5504 5593 5595
 5646 5712 5755 5833 5836 5869 5890 5898 5984 5986 6032 6036 6038 6043
 6056 6076 6083 6088 6112 6149 6161 6247 6268 6332 6345 6352 6354 6359
 6412 6415 6423 6444 6495 6516 6519 6529 6539 6571 6604 6610 6637 6662
 6665]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200821.nc4
[3222 3327 3389 3599 3790 3897 3937 3971 3998 

2020-08-24
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200824.nc4
[3225 3330 3392 3602 3793 3900 3940 3974 4001 4038 4076 4359 4445 4495
 4907 4916 4970 4972 4989 5031 5075 5088 5090 5150 5152 5153 5171 5192
 5235 5269 5281 5310 5318 5420 5438 5453 5507 5598 5601 5611 5649 5715
 5758 5844 5846 5872 5901 5989 6046 6059 6079 6091 6115 6152 6164 6216
 6250 6271 6277 6335 6362 6418 6426 6447 6498 6522 6532 6542 6574 6613
 6640 6668]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200824.nc4
[3225 3330 3392 3602 3793 3900 3940 3974 4001 4038 4076 4359 4445 4495
 4907 4916 4970 4972 4989 5031 5075 5088 5090 5150 5152 5153 5171 5192
 5235 5269 5281 5310 5318 5420 5438 5453 5507 5598 5601 5611 5649 5715
 5758 5844 5846 5872 5901 5989 6046 6059 6079 6091 6115 6152 6164 6216
 6250 6271 6277 6335 6362 6418 6426 6447 6498 6522 6532 6542 6574 6613
 6640 6668]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200824.nc4
[3225 3330 3392 3602 3793 3900 3940 

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200827.nc4
[3228 3333 3395 3605 3796 3903 3943 3977 4004 4041 4079 4362 4433 4448
 4498 4588 4632 4638 4643 4649 4655 4727 4800 4839 4910 4975 4992 5078
 5174 5195 5272 5284 5313 5321 5423 5441 5456 5510 5604 5614 5652 5718
 5761 5849 5875 5904 5992 6049 6062 6094 6118 6167 6219 6253 6274 6280
 6338 6365 6429 6450 6501 6545 6577 6616 6643 6671 7853]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200827.nc4
[3228 3333 3395 3605 3796 3903 3943 3977 4004 4041 4079 4362 4433 4448
 4498 4588 4632 4638 4643 4649 4655 4727 4800 4839 4910 4975 4992 5078
 5174 5195 5272 5284 5313 5321 5423 5441 5456 5510 5604 5614 5652 5718
 5761 5849 5875 5904 5992 6049 6062 6094 6118 6167 6219 6253 6274 6280
 6338 6365 6429 6450 6501 6545 6577 6616 6643 6671 7853]
2020-08-27
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200827.nc4
[3229 3334 3396 3606 3797 3904 3944 3978 4005 4042 4080 4363 4434 4449
 4499 4589 4644 4

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20200830.nc4
[3231 3336 3398 3608 3799 3946 3980 4007 4044 4082 4436 4451 4501 4591
 4646 4652 4658 4729 4808 4814 4836 4881 4904 4913 4939 4941 4978 4995
 4997 5034 5062 5071 5081 5094 5149 5198 5243 5275 5287 5324 5392 5426
 5444 5459 5513 5607 5617 5655 5721 5764 5852 5878 5907 5995 6065 6097
 6121 6170 6222 6256 6283 6341 6346 6368 6432 6453 6504 6548 6580 6619
 6646 6674 7066 7856]
2020-08-30
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20200830.nc4
[3232 3337 3399 3609 3800 3947 3981 4008 4045 4083 4437 4452 4502 4592
 4659 4730 4809 4815 4882 4905 4914 4918 4942 4979 4996 4998 5019 5028
 5035 5063 5072 5082 5095 5199 5244 5288 5325 5393 5427 5460 5514 5608
 5618 5656 5722 5765 5853 5879 5908 5996 6066 6098 6122 6171 6223 6257
 6284 6369 6433 6454 6505 6549 6581 6620 6647 6675 7067 7857]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20200830.nc4
[3232 3337 3399 3609 3800 3947 3981 4008 4045 4

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx.20200902.nc4
[3235 3340 3402 3612 3803 3984 4011 4048 4086 4197 4440 4455 4505 4583
 4595 4662 4733 4772 4774 4775 4781 4783 4784 4793 4818 4842 4885 4921
 4945 4982 5001 5022 5038 5066 5085 5098 5202 5247 5291 5328 5396 5430
 5463 5517 5621 5659 5725 5768 5856 5882 5911 5999 6069 6125 6174 6226
 6260 6287 6372 6436 6457 6508 6552 6584 6623 6650 7070 7860]
2020-09-03
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst1_2d_lfo_Nx.20200903.nc4
[3235 3340 3402 3612 3803 3984 4011 4048 4086 4197 4440 4455 4505 4583
 4595 4662 4733 4772 4774 4775 4781 4783 4784 4793 4818 4842 4885 4921
 4945 4982 5001 5022 5038 5066 5085 5098 5202 5247 5291 5328 5396 5430
 5463 5517 5621 5659 5725 5768 5856 5882 5911 5999 6069 6125 6174 6226
 6260 6287 6372 6436 6457 6508 6552 6584 6623 6650 7070 7860]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200903.nc4
[3235 3340 3402 3612 3803 3984 4011 4048 4086 4197 4440 4455 4505 4583
 4595 4

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200906.nc4
[3238 3343 3405 3615 3806 3987 4014 4051 4089 4200 4443 4458 4508 4586
 4598 4665 4736 4787 4791 4796 4821 4845 4888 4924 4948 4985 5004 5025
 5041 5069 5101 5205 5250 5294 5331 5399 5433 5466 5520 5624 5662 5728
 5771 5859 5885 5914 6002 6072 6128 6177 6229 6290 6375 6460 6511 6555
 6587 6626 6653 6886 6887 6890 7035 7073 7082 7192 7863 7990]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx.20200906.nc4
[3238 3343 3405 3615 3806 3987 4014 4051 4089 4200 4443 4458 4508 4586
 4598 4665 4736 4787 4791 4796 4821 4845 4888 4924 4948 4985 5004 5025
 5041 5069 5101 5205 5250 5294 5331 5399 5433 5466 5520 5624 5662 5728
 5771 5859 5885 5914 6002 6072 6128 6177 6229 6290 6375 6460 6511 6555
 6587 6626 6653 6886 6887 6890 7035 7073 7082 7192 7863 7990]
2020-09-06
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst1_2d_lfo_Nx.20200906.nc4
[3239 3344 3406 3616 3807 3988 4015 4052 4090 4201 4444 4459 4509 4587
 4599 4

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200909.nc4
[3241 3346 3618 3809 4017 4054 4092 4203 4461 4511 4601 4668 4739 4824
 4848 4891 4927 4951 5007 5044 5104 5208 5253 5334 5402 5469 5523 5627
 5665 5731 5774 5917 6005 6131 6180 6232 6293 6378 6463 6514 6558 6590
 6629 6656 6737 6749 6756 6776 6780 6790 6796 6799 6838 6841 6893 6984
 7038 7046 7053 7058 7060 7076 7085 7135 7167 7197 7201 7260 7263 7294
 7374 7421 7493 7522 7575 7577 7579 7591 7638 7650 7654 7688 7692 7757
 7758 7792 7839 7866 7993 8075]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx.20200909.nc4
[3241 3346 3618 3809 4017 4054 4092 4203 4461 4511 4601 4668 4739 4824
 4848 4891 4927 4951 5007 5044 5104 5208 5253 5334 5402 5469 5523 5627
 5665 5731 5774 5917 6005 6131 6180 6232 6293 6378 6463 6514 6558 6590
 6629 6656 6737 6749 6756 6776 6780 6790 6796 6799 6838 6841 6893 6984
 7038 7046 7053 7058 7060 7076 7085 7135 7167 7197 7201 7260 7263 7294
 7374 7421 7493 7522 7575 7577 7579 7591 

2020-09-12
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst1_2d_lfo_Nx.20200912.nc4
[3244 3349 3621 3812 4020 4057 4095 4206 4464 4514 4604 4671 4742 4827
 4851 4894 4930 4954 5010 5047 5107 5211 5256 5337 5405 5472 5526 5630
 5668 5734 5777 5920 6008 6134 6183 6235 6296 6381 6466 6561 6593 6632
 6659 6740 6752 6759 6793 6802 6844 6896 6987 7041 7049 7056 7063 7080
 7088 7138 7170 7200 7204 7266 7297 7377 7424 7496 7509 7525 7582 7594
 7641 7657 7695 7727 7795 7869 7996]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200912.nc4
[3244 3349 3621 3812 4020 4057 4095 4206 4464 4514 4604 4671 4742 4827
 4851 4894 4930 4954 5010 5047 5107 5211 5256 5337 5405 5472 5526 5630
 5668 5734 5777 5920 6008 6134 6183 6235 6296 6381 6466 6561 6593 6632
 6659 6740 6752 6759 6793 6802 6844 6896 6987 7041 7049 7056 7063 7080
 7088 7138 7170 7200 7204 7266 7297 7377 7424 7496 7509 7525 7582 7594
 7641 7657 7695 7727 7795 7869 7996]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx

2020-09-15
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst1_2d_lfo_Nx.20200915.nc4
[3247 3352 3624 3815 4023 4060 4098 4209 4467 4517 4607 4674 4745 4830
 4854 4897 4933 4957 5013 5050 5110 5214 5259 5340 5408 5475 5529 5633
 5671 5737 5780 5923 6011 6137 6186 6238 6299 6384 6469 6564 6681 6711
 6743 6766 6805 6832 6833 6847 6874 6875 6899 7044 7052 7091 7141 7173
 7207 7269 7300 7380 7427 7499 7512 7528 7585 7597 7644 7660 7698 7730
 7798 7872 7999]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200915.nc4
[3247 3352 3624 3815 4023 4060 4098 4209 4467 4517 4607 4674 4745 4830
 4854 4897 4933 4957 5013 5050 5110 5214 5259 5340 5408 5475 5529 5633
 5671 5737 5780 5923 6011 6137 6186 6238 6299 6384 6469 6564 6681 6711
 6743 6766 6805 6832 6833 6847 6874 6875 6899 7044 7052 7091 7141 7173
 7207 7269 7300 7380 7427 7499 7512 7528 7585 7597 7644 7660 7698 7730
 7798 7872 7999]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx.20200915.nc4
[3247 3352 3624 3815 4023 

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200918.nc4
[3250 3355 3627 3818 4063 4101 4212 4470 4520 4610 4677 4748 4833 4857
 4900 4936 4960 5016 5053 5113 5217 5262 5343 5411 5478 5532 5636 5674
 5740 5783 5926 6014 6140 6189 6241 6302 6387 6472 6567 6684 6708 6714
 6746 6764 6784 6809 6850 6878 6902 6991 6993 6997 7000 7094 7144 7176
 7210 7272 7303 7383 7430 7502 7515 7531 7588 7600 7647 7663 7701 7733
 7801 7875 8002]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx.20200918.nc4
[3250 3355 3627 3818 4063 4101 4212 4470 4520 4610 4677 4748 4833 4857
 4900 4936 4960 5016 5053 5113 5217 5262 5343 5411 5478 5532 5636 5674
 5740 5783 5926 6014 6140 6189 6241 6302 6387 6472 6567 6684 6708 6714
 6746 6764 6784 6809 6850 6878 6902 6991 6993 6997 7000 7094 7144 7176
 7210 7272 7303 7383 7430 7502 7515 7531 7588 7600 7647 7663 7701 7733
 7801 7875 8002]
2020-09-18
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst1_2d_lfo_Nx.20200918.nc4
[3251 3356 3628 3819 4102 

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200921.nc4
[3254 3631 3822 4105 4216 4474 4524 4614 4681 4752 4861 4964 5057 5117
 5221 5347 5482 5536 5678 5744 5787 5930 6018 6144 6193 6306 6391 6476
 6688 6718 6788 6813 6854 6882 6906 7004 7098 7148 7180 7214 7276 7307
 7387 7434 7506 7519 7535 7604 7667 7705 7737 7805 7879 8006]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx.20200921.nc4
[3254 3631 3822 4105 4216 4474 4524 4614 4681 4752 4861 4964 5057 5117
 5221 5347 5482 5536 5678 5744 5787 5930 6018 6144 6193 6306 6391 6476
 6688 6718 6788 6813 6854 6882 6906 7004 7098 7148 7180 7214 7276 7307
 7387 7434 7506 7519 7535 7604 7667 7705 7737 7805 7879 8006]
2020-09-22
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst1_2d_lfo_Nx.20200922.nc4
[3254 3631 3822 4105 4216 4474 4524 4614 4681 4752 4861 4964 5057 5117
 5221 5347 5482 5536 5678 5744 5787 5930 6018 6144 6193 6306 6391 6476
 6688 6718 6788 6813 6854 6882 6906 7004 7098 7148 7180 7214 7276 7307
 7387 7

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200925.nc4
[3258 3635 3826 4109 4220 4478 4528 4618 4685 4756 4865 4968 5121 5225
 5351 5486 5540 5682 5748 5791 5934 6022 6197 6310 6395 6480 6692 6722
 6772 6817 6858 6910 7008 7102 7152 7184 7218 7280 7311 7391 7438 7539
 7608 7671 7709 7741 7817 7822 7883 7965 8010]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx.20200925.nc4
[3258 3635 3826 4109 4220 4478 4528 4618 4685 4756 4865 4968 5121 5225
 5351 5486 5540 5682 5748 5791 5934 6022 6197 6310 6395 6480 6692 6722
 6772 6817 6858 6910 7008 7102 7152 7184 7218 7280 7311 7391 7438 7539
 7608 7671 7709 7741 7817 7822 7883 7965 8010]
2020-09-26
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst1_2d_lfo_Nx.20200926.nc4
[3258 3635 3826 4109 4220 4478 4528 4618 4685 4756 4865 4968 5121 5225
 5351 5486 5540 5682 5748 5791 5934 6022 6197 6310 6395 6480 6692 6722
 6772 6817 6858 6910 7008 7102 7152 7184 7218 7280 7311 7391 7438 7539
 7608 7671 7709 7741 7817 7822 7883 7

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.tavg1_2d_flx_Nx.20200929.nc4
[3262 3639 3830 4113 4224 4482 4532 4622 4689 4760 4869 5125 5229 5355
 5490 5544 5686 5752 5795 5938 6026 6201 6314 6399 6484 6696 6726 6821
 6862 6914 7012 7106 7156 7188 7222 7284 7315 7395 7442 7543 7612 7675
 7713 7745 7806 7887 7969 7982 8014 8069]
2020-09-30
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst1_2d_lfo_Nx.20200930.nc4
[3262 3639 3830 4113 4224 4482 4532 4622 4689 4760 4869 5125 5229 5355
 5490 5544 5686 5752 5795 5938 6026 6201 6314 6399 6484 6696 6726 6821
 6862 6914 7012 7106 7156 7188 7222 7284 7315 7395 7442 7543 7612 7675
 7713 7745 7806 7887 7969 7982 8014 8069]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_401.inst3_3d_asm_Np.20200930.nc4
[3262 3639 3830 4113 4224 4482 4532 4622 4689 4760 4869 5125 5229 5355
 5490 5544 5686 5752 5795 5938 6026 6201 6314 6399 6484 6696 6726 6821
 6862 6914 7012 7106 7156 7188 7222 7284 7315 7395 7442 7543 7612 7675
 7713 7745 7806 7887 7969 7982 8014 8069]
/data

2020-10-04
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201004.nc4
[3266 3643 3834 4117 4228 4486 4536 4626 4693 4764 4873 5129 5359 5494
 5548 5690 5799 5942 6030 6205 6318 6403 6488 6700 6730 6825 6866 6918
 7016 7110 7160 7226 7288 7319 7399 7446 7547 7616 7679 7717 7749 7891
 7920 7956 7973 7986 8018 8034 8035 8073]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201004.nc4
[3266 3643 3834 4117 4228 4486 4536 4626 4693 4764 4873 5129 5359 5494
 5548 5690 5799 5942 6030 6205 6318 6403 6488 6700 6730 6825 6866 6918
 7016 7110 7160 7226 7288 7319 7399 7446 7547 7616 7679 7717 7749 7891
 7920 7956 7973 7986 8018 8034 8035 8073]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201004.nc4
[3266 3643 3834 4117 4228 4486 4536 4626 4693 4764 4873 5129 5359 5494
 5548 5690 5799 5942 6030 6205 6318 6403 6488 6700 6730 6825 6866 6918
 7016 7110 7160 7226 7288 7319 7399 7446 7547 7616 7679 7717 7749 7891
 7920 7956 7973 7986 8018 8034 8035 8073]
2020-

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201008.nc4
[3270 3647 3838 4121 4232 4490 4540 4630 4697 4768 4877 5133 5363 5498
 5552 5694 5803 5946 6209 6322 6407 6492 6704 6734 6829 6870 6922 7020
 7114 7164 7230 7292 7323 7403 7450 7551 7620 7683 7721 7753 7781 7810
 7812 7814 7825 7829 7831 7840 7895 7924 7960 8022 8039]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201008.nc4
[3270 3647 3838 4121 4232 4490 4540 4630 4697 4768 4877 5133 5363 5498
 5552 5694 5803 5946 6209 6322 6407 6492 6704 6734 6829 6870 6922 7020
 7114 7164 7230 7292 7323 7403 7450 7551 7620 7683 7721 7753 7781 7810
 7812 7814 7825 7829 7831 7840 7895 7924 7960 8022 8039]
2020-10-08
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201008.nc4
[3271 3648 3839 4122 4233 4491 4541 4631 4698 4769 4878 5134 5364 5499
 5553 5695 5804 5947 6210 6323 6408 6705 6735 6830 6871 6923 7021 7115
 7165 7231 7293 7324 7404 7451 7552 7621 7684 7722 7754 7782 7826 7832
 7841 7896 7925 7

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201013.nc4
[3275 3652 3843 4126 4237 4545 4702 5138 5368 5557 5699 5808 5951 6927
 7025 7119 7235 7328 7408 7455 7556 7625 7836 7850 7900 7929 7964 8027]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201013.nc4
[3275 3652 3843 4126 4237 4545 4702 5138 5368 5557 5699 5808 5951 6927
 7025 7119 7235 7328 7408 7455 7556 7625 7836 7850 7900 7929 7964 8027]
2020-10-13
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201013.nc4
[3276 3653 3844 4127 4238 4546 4703 5139 5369 5558 5700 5809 5952 6928
 7026 7120 7236 7329 7409 7456 7557 7626 7837 7851 7901 7930 8028]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201013.nc4
[3276 3653 3844 4127 4238 4546 4703 5139 5369 5558 5700 5809 5952 6928
 7026 7120 7236 7329 7409 7456 7557 7626 7837 7851 7901 7930 8028]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201013.nc4
[3276 3653 3844 4127 4238 4546 4703 5139 5369 5558 5700 5809 5

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201019.nc4
[3281 3658 3849 4132 4243 4551 4708 5144 5374 5563 5705 5814 5957 6933
 7031 7125 7241 7334 7414 7461 7562 7631 7764 7767 7775 7906 7935 8033
 8045 8049 8053 8060 8080]
2020-10-19
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201019.nc4
[3282 3659 3850 4133 4244 4552 4709 5145 5375 5564 5706 5815 5958 6934
 7032 7126 7242 7335 7415 7462 7563 7632 7765 7768 7776 7786 7788 7907
 7936 8046 8050 8054 8061 8081]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201019.nc4
[3282 3659 3850 4133 4244 4552 4709 5145 5375 5564 5706 5815 5958 6934
 7032 7126 7242 7335 7415 7462 7563 7632 7765 7768 7776 7786 7788 7907
 7936 8046 8050 8054 8061 8081]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201019.nc4
[3282 3659 3850 4133 4244 4552 4709 5145 5375 5564 5706 5815 5958 6934
 7032 7126 7242 7335 7415 7462 7563 7632 7765 7768 7776 7786 7788 7907
 7936 8046 8050 8054 8061 8081]
2020-1

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201025.nc4
[3288 3665 3856 4139 4250 4558 4715 5381 5570 5821 5964 6940 7132 7248
 7341 7468 7569 7913 7942 8087 8148]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201025.nc4
[3288 3665 3856 4139 4250 4558 4715 5381 5570 5821 5964 6940 7132 7248
 7341 7468 7569 7913 7942 8087 8148]
2020-10-26
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201026.nc4
[3288 3665 3856 4139 4250 4558 4715 5381 5570 5821 5964 6940 7132 7248
 7341 7468 7569 7913 7942 8087 8148]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201026.nc4
[3288 3665 3856 4139 4250 4558 4715 5381 5570 5821 5964 6940 7132 7248
 7341 7468 7569 7913 7942 8087 8148]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201026.nc4
[3288 3665 3856 4139 4250 4558 4715 5381 5570 5821 5964 6940 7132 7248
 7341 7468 7569 7913 7942 8087 8148]
2020-10-26
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201026.nc4


/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201102.nc4
[3295 3672 3863 4146 4257 4565 4722 5388 5577 5828 5971 6947 7255 7348
 7475 7949 8101 8104 8126 8155]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201102.nc4
[3295 3672 3863 4146 4257 4565 4722 5388 5577 5828 5971 6947 7255 7348
 7475 7949 8101 8104 8126 8155]
2020-11-02
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201102.nc4
[3296 3673 3864 4147 4258 4566 4723 5389 5578 5829 5972 6948 7256 7349
 7476 7950 8102 8105 8127 8145 8156]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201102.nc4
[3296 3673 3864 4147 4258 4566 4723 5389 5578 5829 5972 6948 7256 7349
 7476 7950 8102 8105 8127 8145 8156]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201102.nc4
[3296 3673 3864 4147 4258 4566 4723 5389 5578 5829 5972 6948 7256 7349
 7476 7950 8102 8105 8127 8145 8156]
2020-11-03
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201103.nc4
[3296 3673

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201111.nc4
[4267 4575 5587 6957 7358 7485]
2020-11-12
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201112.nc4
[4267 4575 5587 6957 7358 7485]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201112.nc4
[4267 4575 5587 6957 7358 7485]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201112.nc4
[4267 4575 5587 6957 7358 7485]
2020-11-12
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201112.nc4
[4268 4576 5588 6958 7359 7486]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201112.nc4
[4268 4576 5588 6958 7359 7486]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201112.nc4
[4268 4576 5588 6958 7359 7486]
2020-11-13
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201113.nc4
[4268 4576 5588 6958 7359 7486]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201113.nc4
[4268 4576 5588 6958 7359 7486]
/data2/lthapa/2020/MER

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201126.nc4
[4281 6971]
2020-11-26
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201126.nc4
[4282 6972]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201126.nc4
[4282 6972]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201126.nc4
[4282 6972]
2020-11-27
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201127.nc4
[4282 6972]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201127.nc4
[4282 6972]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201127.nc4
[4282 6972]
2020-11-27
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201127.nc4
[4283 6973]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201127.nc4
[4283 6973]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201127.nc4
[4283 6973]
2020-11-28
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201128.nc4
[4283 6973]
/data2/lthapa/2020/ME

/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201213.nc4
[8157]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201213.nc4
[8157]
2020-12-14
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201214.nc4
[8157]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201214.nc4
[8157]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201214.nc4
[8157]
2020-12-24
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201224.nc4
[8158 8160]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201224.nc4
[8158 8160]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201224.nc4
[8158 8160]
2020-12-25
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst1_2d_lfo_Nx.20201225.nc4
[8158 8160]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.inst3_3d_asm_Np.20201225.nc4
[8158 8160]
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20201225.nc4
[8158 8160]
2020-12-25
/data2/lthapa/2020/MERRA2/WESTUS_MERRA2_400.in

Incident Number      Fire Name Current Day   Lat Fire    Lon Fire  \
0          10662684.0  PAINTED WAGON  2019-04-08  33.786944 -112.753333   
1          10663171.0  LONE MOUNTAIN  2019-06-09  33.808056 -105.738611   
2          10663171.0  LONE MOUNTAIN  2019-06-10  33.808056 -105.738611   
3          10663171.0  LONE MOUNTAIN  2019-06-11  33.808056 -105.738611   
4          10663171.0  LONE MOUNTAIN  2019-06-12  33.808056 -105.738611   
...               ...            ...         ...        ...         ...   
8156       11979237.0          Trail  2020-11-02  34.147222 -112.117778   
8157       11980186.0      SANDERSON  2020-12-13  33.889444 -117.070833   
8158       11980587.0        CREEK 5  2020-12-24  33.402646 -117.266795   
8159       11980587.0        CREEK 5  2020-12-25  33.402646 -117.266795   
8160       11980949.0        CREEK 5  2020-12-24  33.407667 -117.269667   

      Number of VIIRS points  TLML_12Z_0  QLML_12Z_0  SPEEDLML_12Z_0  \
0                        3.0  290.748108    0.004608       10.770707   
1                        2.0  290.003723    0.003563        8.092171   
2                        0.0  281.681793    0.006098       10.386342   
3                        0.0  283.622253    0.009279        6.614388   
4                        0.0  284.536926    0.006591       12.682461   
...                      ...         ...         ...             ...   
8156                     2.0  293.930328    0.003627        7.339819   
8157                    11.0  279.254852    0.001604        6.979411   
8158                     2.0  288.125366    0.001511       10.678336   
8159                    16.0  287.946075    0.002882        5.147175   
8160                     2.0  288.125366    0.001511       10.678336   

          PS_12Z_0  ...  TLML_12Z_1  QLML_12Z_1  SPEEDLML_12Z_1      PS_12Z_1  \
0     91644.742188  ...  295.369202    0.004046        2.791465  91247.414062   
1     81498.414062  ...  281.681793    0.006098       10.386342  82444.875000   
2     82444.875000  ...  283.622253    0.009279        6.614388  81877.890625   
3     81877.890625  ...  284.536926    0.006591       12.682461  81796.609375   
4     81796.609375  ...  287.119812    0.010711        7.384966  81625.007812   
...            ...  ...         ...         ...             ...           ...   
8156  91107.664062  ...  292.495758    0.003988        8.028451  90745.757812   
8157  90997.539062  ...  279.923187    0.006894        4.845186  90440.250000   
8158  99387.382812  ...  287.946075    0.002882        5.147175  99128.710938   
8159  99128.710938  ...  286.868256    0.006895        1.817556  99087.804688   
8160  99387.382812  ...  287.946075    0.002882        5.147175  99128.710938   

      T_12Z_700mb_1  T_12Z_500mb_1  QV_12Z_700mb_1  PBLH_12Z_1  TCZPBL_12Z_1  \
0        281.512573     261.920410        0.002269  253.785019     86.841118   
1        281.240356     262.869751        0.007128  456.560364    585.127686   
2        283.966187     263.090515        0.005877  113.951096    175.440399   
3        284.776917     267.068909        0.004644  314.892853    670.379883   
4        284.941650     263.945251        0.006071  377.865326    376.500244   
...             ...            ...             ...         ...           ...   
8156     281.944702     259.631042        0.003883   64.640175    216.664398   
8157     275.328552     256.890869        0.000052  163.259155    575.620300   
8158     272.194824     258.612366        0.002691  328.705231    123.513199   
8159     276.881714     259.645477        0.002607   63.415359     78.658180   
8160     272.194824     258.612366        0.002691  328.705231    123.513199   

                                               geometry  
0     POLYGON ((-112.75455 33.78632, -112.76012 33.7...  
1     POLYGON ((-105.73275 33.80235, -105.73861 33.8...  
2     POLYGON ((-105.73275 33.80235, -105.73861 33.8...  
3     POLYGON ((-105.73275 33.80235, -105.73861 33.8...  
4     POLYGON ((

In [21]:
dataset = nc.Dataset('/data2/lthapa/2019/MERRA2/WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190109.nc4')
print(dataset)
print(dataset['TCZPBL'][:])

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    History: Fri Jul 30 13:17:37 2021: ncks -d lon,-125.0,-101.0 -d lat,31.0,49.0 -v lat,lon,PBLH,TCZPBL MERRA2_400.tavg1_2d_flx_Nx.20190109.nc4 WESTUS_MERRA2_400.tavg1_2d_flx_Nx.20190109.nc4
Original file generated: Fri Feb  1 22:29:13 2019 GMT
    Comment: GMAO filename: d5124_m2_jan10.tavg1_2d_flx_Nx.20190109.nc4
    Filename: MERRA2_400.tavg1_2d_flx_Nx.20190109.nc4
    Conventions: CF-1
    Institution: NASA Global Modeling and Assimilation Office
    References: http://gmao.gsfc.nasa.gov
    Format: NetCDF-4/HDF-5
    SpatialCoverage: global
    VersionID: 5.12.4
    TemporalRange: 1980-01-01 -> 2016-12-31
    identifier_product_doi_authority: http://dx.doi.org/
    ShortName: M2T1NXFLX
    GranuleID: MERRA2_400.tavg1_2d_flx_Nx.20190109.nc4
    ProductionDateTime: Original file generated: Fri Feb  1 22:29:13 2019 GMT
    LongName: MERRA2 tavg1_2d_flx_Nx: 2d,1-Hourly,Time-Averaged,Single-Level,Ass

In [21]:
fire_features
therest = fire_features[['Incident Number', 'Fire Name', 'Current Day', 'Lat Fire', 'Lon Fire', 'Number of VIIRS points','TLML_12Z_0', 'QLML_12Z_0','SPEEDLML_12Z_0','PS_12Z_0','T_12Z_700mb_0','T_12Z_500mb_0','QV_12Z_700mb_0','PBLH_12Z_0', 'TCZPBL_12Z_0','TLML_12Z_1', 'QLML_12Z_1', 'SPEEDLML_12Z_1','PS_12Z_1','T_12Z_700mb_1','T_12Z_500mb_1','QV_12Z_700mb_1','PBLH_12Z_1', 'TCZPBL_12Z_1']]
print(therest)
therest.to_csv('fire_features_merra.csv', index=False)

      Incident Number      Fire Name Current Day   Lat Fire    Lon Fire  \
0          10662684.0  PAINTED WAGON  2019-04-08  33.786944 -112.753333   
1          10663171.0  LONE MOUNTAIN  2019-06-09  33.808056 -105.738611   
2          10663171.0  LONE MOUNTAIN  2019-06-10  33.808056 -105.738611   
3          10663171.0  LONE MOUNTAIN  2019-06-11  33.808056 -105.738611   
4          10663171.0  LONE MOUNTAIN  2019-06-12  33.808056 -105.738611   
...               ...            ...         ...        ...         ...   
8156       11979237.0          Trail  2020-11-02  34.147222 -112.117778   
8157       11980186.0      SANDERSON  2020-12-13  33.889444 -117.070833   
8158       11980587.0        CREEK 5  2020-12-24  33.402646 -117.266795   
8159       11980587.0        CREEK 5  2020-12-25  33.402646 -117.266795   
8160       11980949.0        CREEK 5  2020-12-24  33.407667 -117.269667   

      Number of VIIRS points  TLML_12Z_0  QLML_12Z_0  SPEEDLML_12Z_0  \
0                        3.

## Helper Functions

In [10]:
#this function calculates the area of each grid in a given grid cell
# LAT and LON should be 2d
def calculate_grid_cell_corners(LAT, LON):
    #we will assume the very edges of the polygons don't touch the boundary of the domain
    lat_corners = (LAT[0:(lat.shape[0]-1),  0:(lat.shape[1])-1] + LAT[1:(lat.shape[0]), 1:(lat.shape[1])])/2
    lon_corners = (LON[0:(lat.shape[0]-1),  0:(lat.shape[1])-1] + LON[1:(lat.shape[0]), 1:(lat.shape[1])])/2
    return lat_corners, lon_corners
    """for ii in range(1,LAT.shape[0]-1):
        for jj in range(1, LAT.shape[1]-1):
            cell_lat = LAT[ii, jj]
            cell_lon = LON[ii, jj]
            SW_lat[ii,jj] = LAT[ii,jj] + (LAT[ii-1,jj-1] - LAT[ii,jj])/2
            SW_lon[ii,jj] = LON[ii,jj] + (LON[ii-1,jj-1] - LON[ii,jj])/2
            SE_lat[ii,jj] = LAT[ii,jj] + (LAT[ii-1,jj-1] - LAT[ii,jj])/2
            SE_lon[ii,jj] = LON[ii,jj] + (LON[ii,jj] - LON[ii-1,jj-1])/2
            NW_lat[ii,jj] = LAT[ii,jj] + (LAT[ii,jj] - LAT[ii-1,jj-1])/2
            NW_lon[ii,jj] = LON[ii,jj] + (LON[ii-1,jj-1] - LON[ii,jj])/2
            NE_lat[ii,jj] = LAT[ii,jj] + (LAT[ii,jj] - LAT[ii-1,jj-1])/2
            NE_lon[ii,jj] = LON[ii,jj] + (LON[ii,jj] - LON[ii-1,jj-1])/2
    return  SW_lat, SW_lon, SE_lat, SE_lon, NW_lat, NW_lon, NE_lat, NE_lon"""

In [11]:
# this function calculates the overlap between the given shape (fire_shape) and given grid (LAT, LON). 
#LAT and LON should be 2D

def calculate_overlaps(lat, lon, lat_corners, lon_corners, lat_start, lat_stop, lon_start, lon_stop, fire_shape):
    overlaps = np.zeros(lat.shape)
    # buffer the fire shape so it has a non zero area
    if fire_shape.area ==0:
        fire_shape = fire_shape.buffer(0.01)
    # find the intersection between the first day's polygon and the  grid
    for ii in range(lat_start, lat_stop):
        for jj in range(lon_start, lon_stop):
            #print('ctr', lat[ii,jj], lon[ii,jj])
            """ SW_lat = lat_corners[ii-1, jj-1]
            SW_lon = lon_corners[ii-1, jj-1]
            SE_lat = lat_corners[ii-1, jj-1]
            SE_lon = lon_corners[ii-1, jj]
            NW_lat = lat_corners[ii, jj-1]
            NW_lon = lon_corners[ii, jj-1]
            NE_lat = lat_corners[ii, jj]
            NE_lon = lon_corners[ii, jj]"""
            poly_cell = Polygon([(lon_corners[ii, jj-1],lat_corners[ii, jj-1]), (lon_corners[ii, jj],lat_corners[ii, jj]), (lon_corners[ii-1, jj],lat_corners[ii-1, jj-1]), (lon_corners[ii-1, jj-1], lat_corners[ii-1, jj-1])])
            overlap_cell = fire_shape.intersection(poly_cell)
            #overlaps are the fraction of the POLYGON in each grid cell
            overlaps[ii,jj] = overlap_cell.area/fire_shape.area
    
    return overlaps